### ISSUE TITLE
How to convert mel feature generated from tacotron2 to the one for input of waveglow

### ISSUE THREAD

**Issue by NewEricWang** [NVIDIA/waveglow#101]
Hi,
    I find the format between tacotron2 output and waveglow input is different. How can I convert the Mel feature generated from T2 into the one corresponding to waveglow input?

**Comment by androidof2008** [comment]
#Decode text input and plot results
    mel_outputs, mel_outputs_postnet, _, alignments = model.inference(sequence)

#save mel_outputs_postnet[0] to a file, such as: torch.save(mel_outputs_postnet[0], 'filename.pt')
#this file can be used for the input of waveglow
#It works for me

**Comment by NewEricWang** [comment]
@androidof2008 , Thank you very much! I get it!

**Comment by anupam456** [comment]
Are you able to generate audio from inferred Mel of Tacotron -2 using pretrained waveglow model? I see, these two Mels have different preprocessing and so it produces vert noisy output.
