### ISSUE TITLE
Help converting output from Rayhane-mamah Tacotron 2 to Waveglow input

### ISSUE THREAD

**Issue by rohan6366** [NVIDIA/waveglow#102]
Hey, could I get a little help converting the output of [Rayhane-mamah's ](https://github.com/Rayhane-mamah/Tacotron-2)Tacotron 2 to input for pre-trained waveglow. 
I've attached a sample of the output 

[tacotron_output.zip](https://github.com/NVIDIA/waveglow/files/2948925/tacotron_output.zip)

**Comment by ajaysg** [comment]
why dont you use waveglow's submodule nvidia/tacotron2 itself? just as suggestion

**Comment by rohan6366** [comment]
@ajaysg, that's what I've done now. Though the lack of a pre-trained model to continue training on was what I needed. Training from scratch now.
