### ISSUE TITLE
NaN after 74 iterations, distributional training on 4 Nvidia Tesla V100 GPUs

### ISSUE THREAD

**Issue by deepconsc** [NVIDIA/waveglow#103]
I was playing with WaveGlow, and tried different approaches:

1. Retraining pre-trained model on Georgian language dataset
- Required to convert the checkpoint, absolutely no result, throwed NaNs for every iterations. 
- Exceeded memory limit, while the model was running on 16 vCPU, 24GB RAM, 4 NVIDIA Tesla V100 16 VRAM GPUs, with a batch size 3, 2, 1.

2. Training from scratch on Georgian language dataset
- Throwed NaNs on distribution training after 74 iters.
- In `glow.py` , replaced `torch.logdet(W)` with `torch.det(W).abs().log()` as adviced by @belevtsoff , the same happens

Additionally, the generation time for the inference with the trained model on a Predator laptop with GTX1050ti was 24 seconds for 11-sec audio.

**Comment by belevtsoff** [comment]
Seems like the problem might be with your dataset, because starting from scratch shouldn't give you NaNs, especially so early in training. Have you checked if you have Nans or extreme values in your data? I've common problem is when your data contains exact zeros and then you take log of that when extracting features

**Comment by deepconsc** [comment]
@belevtsoff After pulling some hair from our heads, we understood that our initial wav files were sampled at 48kHZ, and used sox to downsample at 22050. Due to sox error, files were actually converted to zero instances, and there's the issue. 

Thank you for your quick response anyway!

**Comment by belevtsoff** [comment]
Cool :) I guess the issue should be closed now.

**Comment by deepconsc** [comment]
Sure!
