### ISSUE TITLE
Batch inference

### ISSUE THREAD

**Issue by chapter544** [NVIDIA/waveglow#105]
Hi all,
As I understand, waveglow performs mel -> audio in a  'all in one step' fashion (instead of sequential like WaveRNN or nv-wavenet implementation). I have a few questions regarding inference.

1. Should we do inference with a long mel (10-20s) or should we break the long mel into smaller pieces (2-4s) and doing batch inference, and then stitch those small audio segments back? I see just a small inference time gain (10%) in breaking it down into smaller segments vs 1 long mel, which I don't understand why.Also, by splitting the big mels into smaller segments, I have problems in merging the audios back. The merged audio has glitches that are caused by the 'disconnects' between smaller segments, even after I try some overlaps between batches. Are there any thoughts on this?

2. The paper mentioned that the current Pytorch implementation runs at 500KHz on the V100, then later mentioned that the upper bound is about 2MHz. On my 1080Ti, the current Waveglow runs about 80KHz (with the 512->256 channels change). Do you have any thoughts on how we can make WaveGlow more efficient?

Thanks,

**Comment by rafaelvalle** [comment]
1. If you want fast inference, use longer mels.
2. use fp16, warm-start by doing inference on dummy data multiple times, use cudnn benchmark

**Comment by chapter544** [comment]
Thank you @rafaelvalle for your inputs. I will try these approaches, I will report back on how these go.

**Comment by chapter544** [comment]
I did some more experiments, it seems like using longer mels is a better route. Do you have any thoughts or recommendations regarding converting this model to TensorRT (as I was reading that TensorRT gives improvements 1.4x+ improvement)? Thanks.

**Comment by rafaelvalle** [comment]
https://devblogs.nvidia.com/how-to-deploy-real-time-text-to-speech-applications-on-gpus-using-tensorrt/
