### ISSUE TITLE
Can't generate 

### ISSUE THREAD

**Issue by antontc** [NVIDIA/waveglow#107]
Hello. I use the last commit and the last checkpoint, but when I try generate wav I take this error. I use pytorch 1.0, CUDA 8, python 3.6
<img width="563" alt="Screen Shot 2019-03-18 at 2 32 11 PM" src="https://user-images.githubusercontent.com/19586895/54527528-45181a00-498b-11e9-9981-a66589ee5257.png">

**Comment by sameerkhurana10** [comment]
+1
