### ISSUE TITLE
How much hours of dataset required to produce wavenet quality of voice ?

### ISSUE THREAD

**Issue by rishikksh20** [NVIDIA/waveglow#11]
2 hours of dataset is enough for `wavenet` to generate crystal clear quality of audio, so is there any minimum hours of dataset required to produce `wavenet` quality of voice from `waveglow`.

**Comment by RPrenger** [comment]
We haven't actually tried it with smaller data sets.  Tacotron2 was still improving with more data, so we always just used the biggest LJ Speech set for WaveGlow.  But the model shows no signs of overfitting on LJ Speech, so I'm sure you can get away with less than 24 hours.  My hunch is 2 hours would be fine. Though you'll need to train something like Tacotron2 if you're using mels, and that is more data hungry.

**Comment by rafaelvalle** [comment]
Closing. Please re-open if necessary.
