### ISSUE TITLE
Increasing pause after sentences

### ISSUE THREAD

**Issue by Cacozelia** [NVIDIA/waveglow#111]
Hi

I am trying to increase the duration of the pause between sentences generated when using the pretrained model. The model is recognizing periods, but I would like to increase the duration of the pause.

**Comment by rafaelvalle** [comment]
Is this a Tacotron 2 or Waveglow question?

**Comment by Cacozelia** [comment]
Hi @rafaelvalle it's a Tacotron 2 question, in my understanding.

**Comment by rafaelvalle** [comment]
This is the waveglow repo. Ask the question at the Tacotron 2 repo.
