### ISSUE TITLE
denoiser throws error

### ISSUE THREAD

**Issue by EinfachTuen** [NVIDIA/waveglow#112]
when I use denoiser.py with more than 0.0 than i get 
RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor on line 39. 

So seems as the tensor is probably not pushed to the cuda device. 

Traceback (most recent call last):
  File "inference.py", line 85, in <module>
    args.sampling_rate, args.is_fp16, args.denoiser_strength)
  File "inference.py", line 57, in main
    audio = denoiser(audio, denoiser_strength)
  File "C:\Python36\lib\site-packages\torch\nn\modules\module.py", line 489, in                                                       __call__
    result = self.forward(*input, **kwargs)
  File "C:\Projekte\waveglow_combined\denoiser.py", line 39, in forward
    audio_denoised = self.stft.inverse(audio_spec_denoised, audio_angles)
  File "tacotron2\stft.py", line 127, in inverse
    inverse_transform[:, :, approx_nonzero_indices] /= window_sum[approx_nonzero                                                      _indices]
RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor

**Comment by J-Fo-S** [comment]
had same issue, just change all instances of torch.FloatTensor to torch.cuda.FloatTensor - including  torch.from_numpy() as well

**Comment by Kei-ti** [comment]
the tacotron2/stft.py should be modified as follow:
from
window_sum = torch.autograd.Variable(
                torch.from_numpy(window_sum), requires_grad=False)
to
window_sum = torch.autograd.Variable(
                torch.from_numpy(window_sum), requires_grad=False).coda()
Best,

**Comment by J-Fo-S** [comment]
better, thanks

**Comment by EinfachTuen** [comment]
thx now it runs well!

**Comment by Ella77** [comment]
in tacotron2.stft.py 
you can use this code when you are using cpu :) Thx

```
use_cuda = torch.cuda.is_available()
#print(use_cuda) #true when you use gpu
device = torch.device('cuda:0' if use_cuda else 'cpu')
   

window_sum = torch.autograd.Variable(
                torch.from_numpy(window_sum), requires_grad=False).to(device)
```
