### ISSUE TITLE
output audio is in male voice for pretrained models

### ISSUE THREAD

**Issue by sravand93** [NVIDIA/waveglow#116]
Hi,
We have used the pretrained models "tacotron2_statedict.pt" and "waveglow_256channels.pt" for tacotron and waveglow respectively for prediction. But the output voice we are getting is a male voice. so, are the above models trained on LJspeech dataset or any other dataset?. if it is on ljspeech dataset, Please let us know if there are any posible mistakes we are doing.

Also ,we are not getting the same quality of voice as of samples given in the website "https://nv-adlr.github.io/WaveGlow" with the use of the above pretrained models. 

Thanks

**Comment by rafaelvalle** [comment]
The setup on https://github.com/NVIDIA/tacotron2/blob/master/inference.ipynb gives correct outputs.
The samples on the website were produced with the models made publicly available.
