### ISSUE TITLE
How achieve speed reported in paper

### ISSUE THREAD

**Issue by AratorField** [NVIDIA/waveglow#117]
In the paper I have read:

>  Despite the simplicity of the model, our PyTorch implementation synthesizes speech at more than 500kHz on an NVIDIA V100 GPU: more than 25 times faster than real time.

I have waveglow with a smaller number of channels (256) and I could only achieve speed a little faster than real-time. How I can synthesize speech 25 times faster than real-time?

**Comment by rafaelvalle** [comment]
Maximize the memory footprint by using long inputs. Try it with 880 mel frames.

**Comment by AratorField** [comment]
How I can control size of mel frames?

**Comment by rafaelvalle** [comment]
Zero Padding is one option.

**Comment by AratorField** [comment]
Can it be set up somewhere in tacotron hparams or waveglow config?
It is related to ConvTranspose operation?

**Comment by rafaelvalle** [comment]
You will need to create an all zeros matrix and concatenate it to the length dimension of your mel spectrogram before going into waveglow. Aim at having 880 mel frames.

**Comment by AratorField** [comment]
My mel spectrogram size is [1, 80, 1592], to which dimension should I add zeros matrix?

**Comment by rafaelvalle** [comment]
I see, your mel is long enough. The numbers reported on the paper are computed on a Tesla V100.

**Comment by vitaly-zdanevich** [comment]
How fast will be synthesis without GPU, on 3 GHz and 3 GB of RAM?
