### ISSUE TITLE
How to use the pre-trained model to speak custom texts?

### ISSUE THREAD

**Issue by RoelVdP** [NVIDIA/waveglow#118]
I am not following how to use the pre-trained model to speak custom texts? i.e. how could I have the pre-trained model express "hello world"?

**Comment by delgerdalai** [comment]
I should see https://github.com/NVIDIA/tacotron2 inference.ipynb. 
It is exactly what you want (tacotron2 + waveglow ).

**Comment by RoelVdP** [comment]
@delgerdalai thank you very much, got that to work well. That also lead me to https://github.com/NVIDIA/nv-wavenet. While I can get the test demo to work, do you know how to change the actual text with the pre-trained model there? Thank you again

**Comment by delgerdalai** [comment]
@RoelVdP I'm sorry. I haven't tried nv-wavenet before. 

FYI https://github.com/NVIDIA/tacotron2/issues/179#issuecomment-479725919

**Comment by RoelVdP** [comment]
Aha, interesting. Thank you @delgerdalai. I was somehow under the impression that nv-wavenet was a successor of waveglow, but from comment you linked, it seems like waveglow is the successor of [nv-]wavenet (or at least a successor to wavenet and so using nv-wavenet [even if faster?] may be a step back in terms of quality). Perhaps @rafaelvalle can shed some light here? Thank you!

**Comment by rafaelvalle** [comment]
nv-wavenet is nvidia's faster than real-time implementation of wavenet, an autoregressive model.
WaveGlow is a parallel, non-autoregressive model that is faster than wavenet by orders of magnitude.

Take a look at our paper: https://arxiv.org/abs/1811.00002
