### ISSUE TITLE
Loss explodes after 740 epochs

### ISSUE THREAD

**Issue by acrosson** [NVIDIA/waveglow#122]
Hi,

I'm training on a custom dataset. My loss is exploding after 740 epochs. Any ideas on how to fix this?

![loss_graph](https://user-images.githubusercontent.com/4795661/58058906-bad16b00-7b1f-11e9-9452-b0fa6282a629.png)

I've tried changing the the learning rate to `1e-5`  from the best, most-recent checkpoint (~730), and it still explodes.

My config file is the same as master branch.

**Comment by acrosson** [comment]
I removed the `fp16_run` by setting it to false. I was able to train a little bit further, but still running into exploding gradients.

I tried clipping the gradients right before the optimizer.step()
```
torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0) # clip gradient at 1.0
optimizer.step()
```

And now i'm getting `nan` after about a hundred epochs from my last checkpoint

```
21129:  nan
tensor(nan, device='cuda:0', grad_fn=<SubBackward0>) 96000
Traceback (most recent call last):
  File "train.py", line 200, in <module>
    train(num_gpus, args.rank, args.group_name, **train_config)
  File "train.py", line 138, in train
    loss.backward()
  File "/home/user/anaconda3/envs/py36/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/user/anaconda3/envs/py36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: MAGMA gesdd : the updating process of SBDSDC did not converge (error: 3) at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/generic/THCTensorMathMagma.cu:307
```

Any suggestions?

My build:
Python 3.6
Cuda 10.0
Torch 1.1.0

**Comment by rafaelvalle** [comment]
Let's move this conversation here https://github.com/NVIDIA/waveglow/issues/123, given that the topic is similar.
