### ISSUE TITLE
how to set the sigma when training, 1.0 or sqrt(0.5)?

### ISSUE THREAD

**Issue by zhanglq95** [NVIDIA/waveglow#124]
The paper use sqrt(0.5) as sigma, but in the config.json it is 1.0.
In my dataset, i find 1.0 train,0.6 test is better than sqrt(0.5) train,0.6 test at the same iteration(200k/4 batchsize/1 gpu / 8000 audios), should I do more experiment on a lower lr(5e-5)?
So can you give me some advice on the sigma and lr setting, thanks very much!

**Comment by rafaelvalle** [comment]
For training use the default value in this repo, 1.0. 
For inference, take a look at values between 0.6 and 1.0

**Comment by pbansal5** [comment]
Hi. I have noticed a bit of trend in the values of sigma. Shorter utterances are generated well with larger values of sigma and vice-versa. Is this true?
