### ISSUE TITLE
README.md: wrong command to generate audio (waveglow_old.pt is not exists)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [NVIDIA/waveglow#126]
Downloaded from Google Drive model called `waveglow_256channels.pt`.

**Comment by caopan16** [comment]
When I used the pretrained model ''waveglow_256channels.pt'' , it occurs the error: deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 0 got 512. How do you fix it?

**Comment by caopan16** [comment]
> Downloaded from Google Drive model called `waveglow_256channels.pt`.

When I used the pretrained model ''waveglow_256channels.pt'' , it occurs the error: deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 0 got 512. How do you fix it?
