### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by jferrer21** [NVIDIA/waveglow#129]
How does the memory usage is calculated? I noticed that under the RTX Titan the model is using around 14G. How could I maximize the 24G that the card has? The default batch size is 12. Could I increase the batch size to 24?

**Comment by jferrer21** [comment]
How does the memory usage is calculated?  I noticed that under the RTX Titan the model is using around 14G.  How could I maximize the 24G that the card has?  The default batch size is 12.  Could I increase the batch size to 24?

**Comment by rafaelvalle** [comment]
Yes, increase the batch size until you run out of memory.
