### ISSUE TITLE
Bottleneck of wavglow

### ISSUE THREAD

**Issue by ThisIsIsaac** [NVIDIA/waveglow#133]
My colleague -- @minty99 -- and I analyzed computation bottleneck using Nsight Systems of waveglow and wanted to share some interesting results.

## Setting
* `torch.cuda.benchmark = True`
* reasonably long inputs ( few seconds of audio )
* ran 10 times ( excluded the first run from profiling to exclude overhead of `torch.cuda.benchmark` )
* fp16
* V100

## Results
we see that we spend about **35% of time** in memory copy operation `kernelPointwiseApply2::CopyOp`

<img width="968" alt="Screen Shot 2019-07-10 at 11 38 49 AM" src="https://user-images.githubusercontent.com/49523965/60941737-17c8f080-a31b-11e9-8e80-842bb0475b18.png">

And here is the profiled output from Nsight Systems.

[waveglow_long_benchmark.qdrep.zip](https://github.com/NVIDIA/waveglow/files/3375795/waveglow_long_benchmark.qdrep.zip)

## Solution
we are discussing with Pytorch team on this [issue](https://github.com/pytorch/pytorch/issues/22612) on optimizing `CopyOp` since it is not fully utilizing the bandwidth for `half` and `int8` types. From some further internal profiling of pytorch `CopyOp`kernel, we expect to see at least **~5%** improvement or more.

**Comment by rafaelvalle** [comment]
@ThisIsIsaac Were you about to solve this issue with the PyTorch team?

**Comment by ThisIsIsaac** [comment]
No. Optimizing would require  specific functions optimized for different input types, and the Pytorch team preferred code simplicity and ease of maintenance over throughput acceleration.
