### ISSUE TITLE
How were the tacotron + WaveGlow samples generated?

### ISSUE THREAD

**Issue by TheButlah** [NVIDIA/waveglow#135]
Hi, and thanks for the great work :)

On the website, there are a couple of Tacotron2 + WaveGlow samples, but there is no explanation as to how exactly these were done. I have the following questions about this demo:

1. Was WaveGlow trained on the GTA spectrograms from a Tacotron2 implementation, or on the ground truth spectrograms? 
2. If (1) is true, was WaveGlow fine tuned from a version trained on ground truth spectrograms, or trained fully from scratch on the GTA spectrograms?
3. Was the synthesizer and vocoder trained separately or jointly? That is, was tacotron2 first trained and then WaveGlow, or were they trained end-to-end where the gradients back-propagated through both models?

Thanks!

**Comment by rafaelvalle** [comment]
1 and 2) Our LJS WaveGlow was trained from scratch on ground truth spectrograms.
3) Tacotron 2 and Waveglow were trained separately.
