### ISSUE TITLE
KeyError 'iteration'

### ISSUE THREAD

**Issue by deepconsc** [NVIDIA/waveglow#136]
In conda environment, using all required packages, waveglow throws error like this:

```
Traceback (most recent call last):
  File "train.py", line 188, in <module>
    train(num_gpus, args.rank, args.group_name, **train_config)
  File "train.py", line 90, in train
    optimizer)
  File "train.py", line 44, in load_checkpoint
    iteration = checkpoint_dict['iteration']
KeyError: 'iteration'
```
I'm using your pre-trained model.

The command:
`python3 distributed.py -c config.json`

**Comment by rafaelvalle** [comment]
The pretrained model does not have iterations, etc in it's dictionary.
If you're using the pretrained model to warm start a new model, you can comment out the keys that do not exist in the pre-trained model's dictionary.

**Comment by crackedeggs1** [comment]
Having this same issue (KeyError 'iteration'), when setting the checkpoint_path to the pre-trained waveglow_256channels_unversal_v5.pt. Where do I "comment out" these keys? My config.json doesn't have them. My training_files is just a list of WAV filenames. Everything else is a default waveglow installation inside Anaconda. What am I missing?

**Comment by gb-ey** [comment]
> Having this same issue (KeyError 'iteration'), when setting the checkpoint_path to the pre-trained waveglow_256channels_unversal_v5.pt. Where do I "comment out" these keys? My config.json doesn't have them. My training_files is just a list of WAV filenames. Everything else is a default waveglow installation inside Anaconda. What am I missing?

Did you found a solution? Would love to here the info!

**Comment by adrianastan** [comment]
Here https://github.com/NVIDIA/waveglow/blob/8afb643df59265016af6bd255c7516309d675168/train.py#L44
