### ISSUE TITLE
Inference time is slow

### ISSUE THREAD

**Issue by ajaysg** [NVIDIA/waveglow#137]
i am using Nvidia Tesla k20xm(Compute Capability 3.5) with 6GB for inference. One word takes 1 sec for inference with waveglow model. A sentence with 6 words take minimum 7 secs. Is there a way to reduce the inference time?

**Comment by rafaelvalle** [comment]
You can maximize the memory footprint of the GPU, that is, provide the GPU with as much data as possible right before it runs out of memory.

**Comment by EuphoriaCelestial** [comment]
> You can maximize the memory footprint of the GPU, that is, provide the GPU with as much data as possible right before it runs out of memory.

and how exactly can I do it? I need some more explain please.
