### ISSUE TITLE
Resume checkpoint on different number of GPUs, batch size

### ISSUE THREAD

**Issue by feddybear** [NVIDIA/waveglow#140]
Hi, I am in an environment where the GPU usage activity varies from time to time.  RIght now I am training on a single GPU, which might take 3 weeks until the desired number of iterations (I am seeing improvements but very slow).

So now, I've noticed that more GPUs freed up and I wanted to stop the current training so I can resume the last checkpoint but change some training configuration to fully take advantage of more GPUs and speed up the training and ensure better convergence.  Any pointers in doing this the right way?

**Comment by rafaelvalle** [comment]
Simply resume from the last checkpoint using distributed training and FP16.

**Comment by feddybear** [comment]
Thanks a lot!
