### ISSUE TITLE
What is the correct form of input to be given to waveglow for onnx conversion

### ISSUE THREAD

**Issue by ajaysg** [NVIDIA/waveglow#143]
i used the following script for exporting the waveglow model to pytorch model

waveglow_path = './waveglow_256channels.pt'
waveglow = torch.load(waveglow_path)['model']

mel_extra=torch.tensor(np.full((1,80,222),-10.0)).float()
dummy_input=torch.autograd.Variable(mel_extra).cuda().float()

audio = torch.tensor(np.full((1,222), -0.5)).float()
audio_input = torch.autograd.Variable(audio).cuda().float()

torch.onnx.export(waveglow, ((dummy_input, audio_input),), "./waveglow.onnx")

is it the correct way?.

**Comment by ajaysg** [comment]
@rafaelvalle

**Comment by ajaysg** [comment]
@nvchai

**Comment by rafaelvalle** [comment]
https://devblogs.nvidia.com/how-to-deploy-real-time-text-to-speech-applications-on-gpus-using-tensorrt/
