### ISSUE TITLE
How to determine when training should be stopped? Do I need a verification set in training?

### ISSUE THREAD

**Issue by wizardk** [NVIDIA/waveglow#144]
Currently, I can only see the loss is runing when using waveglow to train a model. The loss is growing larger slightly. I have to run inference to dump some wav files and listen to them from a checkpoint if I want to check up the effect of my model. I know many people suggest to train longer and longer, but I still want to know whether there is a theoretical stop condition instead of experienced and manual.
Thanks.
@rafaelvalle

**Comment by wizardk** [comment]
I got it.
[https://github.com/NVIDIA/waveglow/issues/1](url)

**Comment by aidosRepoint** [comment]
> I got it. [https://github.com/NVIDIA/waveglow/issues/1](url)

the link doesn't lead anywhere. Can you please find that issue again?
