### ISSUE TITLE
is  it support multi-speaker?

### ISSUE THREAD

**Issue by chwbin** [NVIDIA/waveglow#146]
is  it support multi-speaker?

**Comment by Ella77** [comment]
https://github.com/scpark20/waveglow-tensorflow/blob/master/waveglow-multispeaker.ipynb 

I found there are tf examples that include speaker embedding..

**Comment by chwbin** [comment]
thank you very much! I will try it

**Comment by hongchengzhu** [comment]
> thank you very much! I will try it

Hello, have you tried multispeaker setting? Does it works? How its quality?
