### ISSUE TITLE
Train with 24k wav files (like libriTTS)

### ISSUE THREAD

**Issue by Taekyoon** [NVIDIA/waveglow#157]
Anyone who tried to train with 24k sample rate files?
I changed parameters like this way

```
"segment_length": 36000,
"sampling_rate": 24000,
"filter_length": 2048,
"hop_length": 300,
"win_length": 1200,
```

This setup referred by training libriTTS with Mozilla TTS project.
Any advice for setting parameters?

**Comment by Taekyoon** [comment]
I think this problem is going to be solved. I'll share my updates later. 
And now, this issue might not be active.
So I'll close this issue.

**Comment by GinChow** [comment]
> I think this problem is going to be solved. I'll share my updates later.
> And now, this issue might not be active.
> So I'll close this issue.

Hi bro, did you succeed in training 24k with the config above?

**Comment by Taekyoon** [comment]
Yes, it successfully worked.
