### ISSUE TITLE
Cant find WN.cond_layer

### ISSUE THREAD

**Issue by alreadyHehehe** [NVIDIA/waveglow#162]
I just follow the guide and want to generate audio with pre-existing model, but got an exception like title.
Then I found the code glow.py, glow_old.py, and change it to old, finally I got some .wav files, but all noise, so I confused. Anyone have ideas? thx!
<img width="640" alt="glow" src="https://user-images.githubusercontent.com/16949176/66718157-491df480-ee13-11e9-9bae-d3150f69f79b.png">

**Comment by ryul99** [comment]
I had same issue
I solved this with [convert_model.py](https://github.com/NVIDIA/waveglow/blob/master/convert_model.py)
use this as `python3 convert_model.py old_model_path.pt new_model_path.pt`

**Comment by NoahDrisort** [comment]
Solved this by: https://ngc.nvidia.com/catalog/models/nvidia:waveglow_ljs_256channels/files?version=3
