### ISSUE TITLE
[0-1]mel spectrogram unable to get a normal result?

### ISSUE THREAD

**Issue by yanggeng1995** [NVIDIA/waveglow#163]
hello， I use this file to extract mel spectrogram whose range is 0 to 1 https://github.com/yanggeng1995/Simplified_WaveRNN/blob/master/utils/audio.py， however，I find its hard to train waveglow， I can't even get a more normal result. Is there any solution?

**Comment by rafaelvalle** [comment]
Are you training from scratch or fine-tuning?

**Comment by yanggeng1995** [comment]
> Are you training from scratch or fine-tuning?

Not yet,  I just training directly，I can use tensorflow to train normally, but I can't train normally using this repo. I am confused.

**Comment by sharathadavanne** [comment]
Hi @yanggeng1995 did you find a solution for this? I might be facing a similar problem.

**Comment by yanggeng1995** [comment]
I did not find a solution, I re-written it using tensorflow, you can find
it here  https://github.com/yanggeng1995/WaveGlow

yakku <notifications@github.com> 于2020年1月2日周四 下午8:54写道：
