### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by souravdalai** [NVIDIA/waveglow#168]
this is the error i got while training 
my audio data config is 
 "data_config": {
        "segment_length": 16000,
        "sampling_rate": 48000,
        "filter_length": 4096,
        "hop_length": 512,
        "win_length": 4096,
        "mel_fmin": 0.0,
        "mel_fmax": 8000.0}
below to numbers are the lengths of corresponding indexs of spectograms and the audio
print(spect.size(2))
print(audio.size(1))

8960
16000
Traceback (most recent call last):
  File "train.py", line 193, in <module>
    train(num_gpus, args.rank, args.group_name,training_folder, **train_config)
  File "train.py", line 124, in train
    outputs = model((mel, audio))
  File "/root/anaconda3/envs/nvidia/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/speech/Demo/nvidia/tacotron2/waveglow/glow.py", line 218, in forward
    assert(spect.size(2) >= audio.size(1))
AssertionError

Thanks in advance

**Comment by puppyapple** [comment]
@souravdalai hello, any progress in this error? I just run into the same issue here.

**Comment by TheSeeker218** [comment]
> @souravdalai hello, any progress in this error? I just run into the same issue here.
i think the filter length 4096  was too high for 48000 sample rate, so i resampled my data to 22050 sample rate and changed the data config to , 
"data_config": {
"segment_length": 16000,
"sampling_rate": 22050,
"filter_length": 2048,
"hop_length": 256,
"win_length": 2048,
"mel_fmin": 0.0,
"mel_fmax": 8000.0}

**Comment by rafaelvalle** [comment]
Take a look at the pull request below: when changing ``hop_length`` and ``win_length``, you'll need to also change the upsampling layer in the model
https://github.com/NVIDIA/waveglow/pull/88/files#diff-2b3c4fcf550a15d7b23db0a2614c4a95R185
