### ISSUE TITLE
`nan`s in inference with pretrained model

### ISSUE THREAD

**Issue by mcncm** [NVIDIA/waveglow#171]
Hi everyone,

I've been trying to produce audio waveforms with the pretrained model using spectrograms from your (also pretrained) tacotron2 model. Unfortunately, the output of `waveglow.infer` is a rank-1 tensor of plausible length of not-a-numbers. This persists if I replace the spectrogram with an all-zero spectrogram. This looks somewhat reminiscent of some of issues (e.g. #35 ), but I'm not sure exactly what to make of it.

Possibly related: loading the model throws these warnings:

    path/to/my/python3.7/site-packages/torch/serialization.py:435: SourceChangeWarning: source code 
    of class 'glow_old.WaveGlow' has changed. you can retrieve the original source code by accessing the
    object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.

If there's any information that you'd find useful (platform, package versions, etc.), I can definitely provide that.

Thank you!

**Comment by mcncm** [comment]
It turns out I just needed `update_model`, which solves this! False alarm. Thanks.

**Comment by Feywell** [comment]
I encounter the same question. How can you solve this problem. Can you tell me for detail

**Comment by JakubReha** [comment]
same problem, update _model doesn't help. Did you solve it?

**Comment by amirpashamobinitehrani** [comment]
same problem here! Has anyone solved this issue?

**Comment by chiuhans111** [comment]
Although this issue is closed,

The problem may be caused by using the `torch.float16` data type.  
Changing it to `torch.float32` resolved the issue for me.

By modifying the following to the `inference.ipynb`:

1. remove the `.half()`
```py
waveglow.cuda().eval() # .half()
```
2. Convert to `torch.float32` before `infer`
```py
audio = waveglow.infer(mel_outputs_postnet.type(torch.float32), sigma=0.666)
```

Reference: https://github.com/facebookresearch/fairseq/issues/4031#issuecomment-1046282601
> I change only the torch.float16 to torch.float32 and sloved. Because when use torch.float16 this parameters vanishing and in somewhere try to divide zero. I hope it helps your problem too.
