### ISSUE TITLE
torch.backends.cudnn.benchmark = True?

### ISSUE THREAD

**Issue by CookiePPP** [NVIDIA/waveglow#172]
changing line

[`torch.backends.cudnn.benchmark = False`](https://github.com/NVIDIA/waveglow/blob/master/train.py#L187)

to

[`torch.backends.cudnn.benchmark = True`](https://github.com/NVIDIA/waveglow/blob/master/train.py#L187)

Changed my time per iteration from 2.00s to 1.42s.
**Are there any reasons I should avoid changing this line?**

Googling hasn't shown any obvious problems and my WaveGlow seems to be running like normal with this option changed.

EDIT: Seems to have worked well, closing issue as there's not really much to say. Just enable it for a perf bump.

**Comment by v-nhandt21** [comment]
> 

![image](https://user-images.githubusercontent.com/36092323/157642375-de36249f-a10b-4288-83ec-4c9fe8954513.png)

From stackoverflow with love :))
