### ISSUE TITLE
ModuleNotFoundError: No module named 'glow'

### ISSUE THREAD

**Issue by un-knight** [NVIDIA/waveglow#174]
Meet an error when I tried to load [waveglow checkpoint downloaded from NGC](https://ngc.nvidia.com/catalog/models/nvidia:waveglow_ljs_256channels).

Error information is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kk/anaconda3/envs/py3_torch/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/kk/anaconda3/envs/py3_torch/lib/python3.7/site-packages/torch/serialization.py", line 613, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'glow'
```

**Comment by gprachi28** [comment]
@un-knight Did you find any solution? i am facing the same problem

**Comment by liyang619** [comment]
@un-knight @gprachi28 I am facing the same problem, too. Did you solve it?

**Comment by rebryk** [comment]
The thing is that a new WaveGlow checkpoint is generated by [nvidia/waveglow repo](https://github.com/NVIDIA/waveglow). So you can copy [glow.py](https://github.com/NVIDIA/waveglow/blob/master/glow.py) from there, and use [this code](https://github.com/NVIDIA/waveglow/blob/2fd4e63e2918012f55eac2c8a8e75622a39741be/inference.py#L37) to upload the model.

**Comment by rafaelvalle** [comment]
Please use the checkpoint provided [here](https://drive.google.com/file/d/1rpK8CzAAirq9sWZhe9nlfvxMF1dRgFbF/view)

**Comment by chaksam** [comment]
> Please use the checkpoint provided [here](https://drive.google.com/file/d/1rpK8CzAAirq9sWZhe9nlfvxMF1dRgFbF/view)

I downloaded the model from here but still getting the error.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_25490/3452766092.py in <module>
      1 path = "waveglow/waveglow_ljspeech_2/waveglow_256channels_universal_v5.pt"
      2 
----> 3 waveglow = torch.load(path)['model'].state_dict()
      4 waveglow = waveglow.remove_weightnorm(waveglow)
      5 waveglow.cuda().eval()

~/python_envs/tacotron/lib/python3.7/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    606                     return torch.jit.load(opened_file)
    607                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 608         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    609 
    610 

~/python_envs/tacotron/lib/python3.7/site-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    785     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    786     unpickler.persistent_load = persistent_load
--> 787     result = unpickler.load()
    788 
    789     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

ModuleNotFoundError: No module named 'glow'

**Comment by AfrinaVT** [comment]
Can anyone got to solve the problem? I am facing the same problem.

**Comment by akshaayan** [comment]
Same problem here

**Comment by finardi** [comment]
same problem here!

**Comment by finardi** [comment]
with append path to main folder waveglow I've success to load the model 
```
import sys
sys.path.append(path_base+'/waveglow') #where path_base is the path untill main folder

def load_waveglow(waveglow_path):
    waveglow = torch.load(waveglow_path)['model']
    waveglow = waveglow.remove_weightnorm(waveglow)
    waveglow.cuda().eval()
```

**Comment by change93n98** [comment]
@finardi 
Thank you. It worked out the way you did.
Before, sys.path.appeng(relative path) will report an error
After modification, sys.path.appeng(absolute path) has no errors
