### ISSUE TITLE
Questions on Section 2.3 of the paper

### ISSUE THREAD

**Issue by tdeboissiere** [NVIDIA/waveglow#175]
- The current master implementation implements a squeeze operation of size 8, meaning that a batch (B, 16000) of audio gets turned into (B, 8, 2000).
- In Section 2.3, you mention that you do not add any further squeeze operation.

Questions:

- Have you run experiments with different sizes (e.g size 32 instead of 8) ?
- Have you run experiments with additional squeeze operations ?

My intuition would be that more squeezing / larger squeeze sizes would help with the receptive field and overall training But that might not be necessary given the use of the dilated stack ?

**Comment by rafaelvalle** [comment]
Your intuition is correct.
We informally explored different group sizes and got the best quality to inference speed ratio with the current setup.
Please let us know if you find better configurations.
