### ISSUE TITLE
Generate a package tts

### ISSUE THREAD

**Issue by lszyba1** [NVIDIA/waveglow#176]
Hello,
Related to #87, I'm trying to build a package that replaces:
[http://lucasmanual.com/blog/alt-speak-alts-how-to-enable-talk-to-speach/](http://lucasmanual.com/blog/alt-speak-alts-how-to-enable-talk-to-speach/)

The main goal is to improve the "spoken voice". Above(festival) has too "robotic" voice. If I was to pick "waveglow" as a most human like, how can create a package that would allow me to generate audio in a similar style as in talks.sh in above link?

Pros:

Cons:

Thank you
Lucas

**Comment by rafaelvalle** [comment]
https://devblogs.nvidia.com/how-to-deploy-real-time-text-to-speech-applications-on-gpus-using-tensorrt/
