### ISSUE TITLE
How do I output data to tensorboard?

### ISSUE THREAD

**Issue by youmebangbang** [NVIDIA/waveglow#178]
I know from using the tacotron2 model I can use tensorboard to get the data from the logdir.  Is there someway use tensorboard for the waveglow training?  I see no logdir anywhere.

**Comment by CookiePPP** [comment]
https://github.com/NVIDIA/waveglow/blob/master/config.json#L12
Set `with_tensorboard` to `true`
and a directory called "logs" will appear in the same spot logdir would be in tacotron2

**Comment by youmebangbang** [comment]
Thank you, glad to see that was added.
