### ISSUE TITLE
Training fails with torch.jit.script

### ISSUE THREAD

**Issue by dchaws** [NVIDIA/waveglow#18]
I pulled the latest code and now training fails with error:

raise NotSupportedError(base.range(), "slicing multiple dimensions at the same time isn't supported yet")
torch.jit.frontend.NotSupportedError: slicing multiple dimensions at the same time isn't supported yet
@torch.jit.script
def fused_add_tanh_sigmoid_multiply(input_a, input_b,n_channels):
    n_channels_int = n_channels[0]
    in_act = input_a+input_b
    t_act = torch.nn.functional.tanh(in_act[:, :n_channels_int, :])
                                     ~~~~~~ <--- HERE
    s_act = torch.nn.functional.sigmoid(in_act[:,n_channels_int:, :])
    acts = t_act * s_act
    return acts

**Comment by rafaelvalle** [comment]
Thanks for letting us know,. We reverted the PR while working on a solution.

**Comment by rafaelvalle** [comment]
@dchaws Please pull from master and update your pytorch to 1.0

**Comment by Cpruce** [comment]
operation failed in interpreter:
@torch.jit.script
def fused_add_tanh_sigmoid_multiply(input_a, input_b, n_channels):
    n_channels_int = n_channels[0]
    in_act = input_a+input_b
             ~~~~~~~~~~~~~~~ <--- HERE
    t_act = torch.tanh(in_act[:, :n_channels_int, :])
    s_act = torch.sigmoid(in_act[:, n_channels_int:, :])
    acts = t_act * s_act
    return acts

pytorch 1.1

**Comment by WesLee88524** [comment]
update to pytorch-1.0.0 but another question appears ,"ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead."
