### ISSUE TITLE
Cant load waveglow checkpoint into inference code even after convert

### ISSUE THREAD

**Issue by EuphoriaCelestial** [NVIDIA/waveglow#190]
I have trained a new waveglow model for my language, but I cant load it into Tacotron2 `inference.ipynb` file to run test. It return this error:
`AttributeError: 'WN' object has no attribute 'cond_layers'`

I tried convert the checkpoint using `convert_model.py` file in waveglow folder but it still raise the same error

**Comment by Jackson-Kang** [comment]
I met same error. Did you solve the problem?

**Comment by EuphoriaCelestial** [comment]
sadly, no, I have to use the pretrained checkpoint of waveglow

**Comment by CookiePPP** [comment]
The WaveGlow packaged with Tacotron2 is out of date. Update the WaveGlow inside of Tacotron2 to match the WaveGlow you trained with.
https://github.com/NVIDIA/tacotron2/issues/333#issuecomment-613783118

**Comment by Jackson-Kang** [comment]
I change "convert_model.py" into the codes below. 

Since my model has not trained yet, I couldn't test this codes.
Hope that this codes are helpful to you and plz let me know whether it works or not.

Thank you.


```
import sys
import copy
import torch

def _check_model_old_version(model):
    if hasattr(model.WN[0], 'res_layers'):
        return True
    else:
        return False

def update_model(old_model):
    if not _check_model_old_version(old_model):
        return old_model
    new_model = copy.deepcopy(old_model)
    for idx in range(0, len(new_model.WN)):
        wavenet = new_model.WN[idx]
        wavenet.res_skip_layers = torch.nn.ModuleList()
        n_channels = wavenet.n_channels
        n_layers = wavenet.n_layers
        for i in range(0, n_layers):
            if i < n_layers - 1:
                res_skip_channels = 2*n_channels
            else:
                res_skip_channels = n_channels
            res_skip_layer = torch.nn.Conv1d(n_channels, res_skip_channels, 1)
            skip_layer = torch.nn.utils.remove_weight_norm(wavenet.skip_layers[i])
            if i < n_layers - 1:
                res_layer = torch.nn.utils.remove_weight_norm(wavenet.res_layers[i])
                res_skip_layer.weight = torch.nn.Parameter(torch.cat([res_layer.weight, skip_layer.weight]))
                res_skip_layer.bias = torch.nn.Parameter(torch.cat([res_layer.bias, skip_layer.bias]))
            else:
                res_skip_layer.weight = torch.nn.Parameter(skip_layer.weight)
                res_skip_layer.bias = torch.nn.Parameter(skip_layer.bias)
            res_skip_layer = torch.nn.utils.weight_norm(res_skip_layer, name='weight')
            wavenet.res_skip_layers.append(res_skip_layer)
        del wavenet.res_layers
        del wavenet.skip_layers
    return new_model

def _check_model_trained_with_custom_data(model):
    if hasattr(model.WN[0], 'cond_layer'):
        return True
    else:
        return False


def update_model_custom(old_model):
    if not _check_model_trained_with_custom_data(old_model):
        return old_model

    new_model = copy.deepcopy(old_model)

    for idx in range(0, len(new_model.WN)):
        wavenet = new_model.WN[idx]
        wavenet.cond_layers = torch.nn.ModuleList()
        n_channels = wavenet.n_channels
        n_layers = wavenet.n_layers

        removed_weightnorm = torch.nn.utils.remove_weight_norm(wavenet.cond_layer)
        removed_weightnorm.weight = torch.nn.Parameter(removed_weightnorm.weight.view(n_layers, n_channels*2, 640, -1))
        removed_weightnorm.bias = torch.nn.Parameter(removed_weightnorm.bias.view(n_layers, n_channels*2))

        print("{}".format(idx+1))
        for cond_param_name, cond_params in removed_weightnorm.named_parameters():

            #torch.nn.utils.remove_weight_norm()
            if cond_param_name == "bias":
                print("\tcond_layer_param [bias]: ", cond_params.data.size())

            else:
                print("\tweight norm: ", cond_param_name)
                print("\t\tcond_layer_params : ", cond_params.data.size())

            for i in range(0, n_layers):
                conv = torch.nn.Conv1d(640, n_channels*2, 1)
                conv.weight = torch.nn.Parameter(removed_weightnorm.weight[i])
                conv.bias = torch.nn.Parameter(removed_weightnorm.bias[i])
                print("\tconv {}-th size -  \tweight: {}\tbias: {}".format(i, conv.weight.size(), conv.bias.size()))

                conv = torch.nn.utils.weight_norm(conv, name='weight')
                wavenet.cond_layers.append(conv)

        del wavenet.cond_layer
        print("[WN END]\n\n")

    return new_model


if __name__ == '__main__':
    old_model_path = sys.argv[1]
    new_model_path = sys.argv[2]
    model = torch.load(old_model_path)
    model['model'] = update_model(model['model'])
    model['model'] = update_model_custom(model['model'])

    torch.save(model, new_model_path)
```

**Comment by Jackson-Kang** [comment]
> The WaveGlow packaged with Tacotron2 is out of date. Update the WaveGlow inside of Tacotron2 to match the WaveGlow you trained with.
> [NVIDIA/tacotron2#333 (comment)](https://github.com/NVIDIA/tacotron2/issues/333#issuecomment-613783118)

Hi, CokiePPP, 

In my case, I didn't use WaveGlow packaged in Tacotron2. I used the independent WaveGlow code. Therefore, I think that the problem is not form the old WaveGlow code in Tacotron2 package.

**Comment by Jackson-Kang** [comment]
> sadly, no, I have to use the pretrained checkpoint of waveglow

I think that it will may not work if input distribution of mel-spectrogram is different with your preprocessing method or pretrained "Mel-spectrogram generator" such as Tacotron or Tacotron2.

FYI, if you want to work with pretrained model from NVIDIA, "Mel spectrogram generator" must be trained with unnormalized log-melspectrogram.

Thank you.

**Comment by EuphoriaCelestial** [comment]
> I think that pretrained WaveGlow model may not work, if input distribution of mel-spectrogram is different with your preprocessing method, or input distribution for pretrained "Mel-spectrogram generator" such as Tacotron or Tacotron2.
> 
> FYI, if you want to work with pretrained model from NVIDIA, "Mel spectrogram generator" must be trained with unnormalized log-melspectrogram.
> 
> Thank you.

I am using that pretrained WaveGlow model, and it work well with my Tacotron2 model, which I trained from scratch with my own dataset. It just has speed problem, WaveGlow inference is about 4xslower than Tacotron2, and sometimes the audio has echoes. What is possible cause?

**Comment by Jackson-Kang** [comment]
> > I think that pretrained WaveGlow model may not work, if input distribution of mel-spectrogram is different with your preprocessing method, or input distribution for pretrained "Mel-spectrogram generator" such as Tacotron or Tacotron2.
> > FYI, if you want to work with pretrained model from NVIDIA, "Mel spectrogram generator" must be trained with unnormalized log-melspectrogram.
> > Thank you.
> 
> I am using that pretrained WaveGlow model, and it work well with my Tacotron2 model, which I trained from scratch with my own dataset. It just has speed problem, WaveGlow inference is about 4xslower than Tacotron2, and sometimes the audio has echoes. What is possible cause?



You mean that you used pretrained WaveGlow model, so my code needs test, right?


In my experiences, most of speed degragation problem is mostly come from framework version.
Check that your pytorch framework version matches this repos. version, and change it.

**Comment by Jackson-Kang** [comment]
> > I think that pretrained WaveGlow model may not work, if input distribution of mel-spectrogram is different with your preprocessing method, or input distribution for pretrained "Mel-spectrogram generator" such as Tacotron or Tacotron2.
> > FYI, if you want to work with pretrained model from NVIDIA, "Mel spectrogram generator" must be trained with unnormalized log-melspectrogram.
> > Thank you.
> 
> I am using that pretrained WaveGlow model, and it work well with my Tacotron2 model, which I trained from scratch with my own dataset. It just has speed problem, WaveGlow inference is about 4xslower than Tacotron2, and sometimes the audio has echoes. What is possible cause?

Can you show me the attention alignment? I think that "echo" sound can happen when you train the model with few samples or the trained model is undertrained.

If you have a few samples to train, you might use various "transfer-learning" methodologies such as this paper(https://arxiv.org/abs/1808.10128).

**Comment by EuphoriaCelestial** [comment]
> In my experiences, most of speed degragation problem is mostly come from framework version.

Maybe. I am using torch 1.4 and numpy 1.16, meanwhile, in the requirements there are torch 1.0 and numpy 1.13.
But I cant use numpy 1.13, because tensorflow 1.15.2 need numpy higher than 1.15. I dont know how Nvidia get it working with numpy 1.13

**Comment by EuphoriaCelestial** [comment]
> Regarding "echo"sounds, could you show me the attention alignment?

you mean this?
![image](https://user-images.githubusercontent.com/43977734/81524907-22aa4280-937d-11ea-9836-78995e82f23c.png)

It not alway happen, so I can get a plot of echo right now

**Comment by EuphoriaCelestial** [comment]
> > In my experiences, most of speed degragation problem is mostly come from framework version.
> 
> Maybe. I am using torch 1.4 and numpy 1.16, meanwhile, in the requirements there are torch 1.0 and numpy 1.13.
> But I cant use numpy 1.13, because tensorflow 1.15.2 need numpy higher than 1.15. I dont know how Nvidia get it working with numpy 1.13

Update: I tried torch 1.0, the Tacotron inference time is slightly reduced, but Waveglow time is almost doubled

**Comment by Jackson-Kang** [comment]
> > Regarding "echo"sounds, could you show me the attention alignment?
> 
> you mean this?
> ![image](https://user-images.githubusercontent.com/43977734/81524907-22aa4280-937d-11ea-9836-78995e82f23c.png)
> 
> It not alway happen, so I can get a plot of echo right now

In DL-based TTS, "Skipping and repeating(echo)" problem occurs when attention alignment is not diagonal. Also, when training "Mel-spectrogram generator" such as Tacotron2, you must wait until attention is mature even if the model reached minimum point of loss. If not, you may get synthesis audio with various skipping and repeating problem.

However, according to your figures, I think the attention is diagonal and synthesis audio has no repeating(echo) problem. Does it contain echo?

**Comment by Jackson-Kang** [comment]
> > > In my experiences, most of speed degragation problem is mostly come from framework version.
> > 
> > 
> > Maybe. I am using torch 1.4 and numpy 1.16, meanwhile, in the requirements there are torch 1.0 and numpy 1.13.
> > But I cant use numpy 1.13, because tensorflow 1.15.2 need numpy higher than 1.15. I dont know how Nvidia get it working with numpy 1.13
> 
> Update: I tried torch 1.0, the Tacotron inference time is slightly reduced, but Waveglow time is almost doubled

That's weird.. I think that this slow-inference issue is general and it will be good if you refer other issues in this repository. (https://github.com/NVIDIA/waveglow/issues?q=slow+inference)

**Comment by EuphoriaCelestial** [comment]
>  Does it contain echo?

in the audio of this plot, no
but sometime it does. I will try to re create the problem and save the plot result of the echo

> That's weird.. I think that this slow-inference issue is general and it will be good if you refer other issues in this repository. (https://github.com/NVIDIA/waveglow/issues?q=slow+inference)

can you give me the `pip list` result of your running environment?

**Comment by Jackson-Kang** [comment]
> in the audio of this plot, no
> but sometime it does. I will try to re create the problem and save the plot result of the echo

Then, echo problem is due to the Tacotron2 model, not from the source code. If you want to improve them, you have to survey various attention improvement techniques which make attention robust to model long-term sequences.  Or, you just use "reduction factor" in Tacotron. Reduction factor 

> can you give me the pip list result of your running environment?

Here. Hope that this can be helpful.

```
absl-py==0.9.0
aniso8601==8.0.0
attrs==19.3.0
audioread==2.1.8
backcall==0.1.0
beautifulsoup4==4.6.0
bleach==3.1.3
cachetools==4.0.0
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
click==7.1.1
colorama==0.4.3
coloredlogs==10.0
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
Distance==0.1.3
dnspython==1.16.0
editdistance==0.5.3
entrypoints==0.3
et-xmlfile==1.0.1
eventlet==0.25.1
Flask==1.1.1
Flask-Cors==3.0.8
Flask-RESTful==0.3.8
Flask-SocketIO==4.2.1
flask-talisman==0.7.0
g2p-en==2.1.0
g2pK==0.9.3
google-auth==1.11.3
google-auth-oauthlib==0.4.1
greenlet==0.4.15
grpcio==1.27.2
gunicorn==20.0.4
h5py==2.10.0
humanfriendly==8.1
idna==2.9
importlib-metadata==1.5.0
inflect==4.0.0
ipykernel==5.2.0
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
itsdangerous==1.1.0
jamo==0.4.1
jdcal==1.4.1
jedi==0.16.0
Jinja2==2.11.1
joblib==0.14.1
JPype1==0.7.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.0
jupyter-console==6.1.0
jupyter-core==4.6.3
kaldiio==2.15.1
kiwisolver==1.1.0
konlpy==0.5.2
librosa==0.7.1
llvmlite==0.31.0
lxml==4.5.0
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mecab-python===0.996-ko-0.9.2
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
monotonic==1.5
munkres==1.1.2
nbconvert==5.6.1
nbformat==5.0.4
networkx==2.4
nltk==3.4.5
notebook==6.0.3
numba==0.48.0
numpy==1.18.1
oauthlib==3.1.0
olefile==0.46
openpyxl==3.0.3
pandas==1.0.3
pandocfilters==1.4.2
panphon==0.17
parso==0.6.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
prometheus-client==0.7.1
prompt-toolkit==3.0.4
protobuf==3.11.3
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
Pygments==2.6.1
pyparsing==2.4.6
pyrsistent==0.15.7
PySocks==1.7.1
python-dateutil==2.8.1
python-engineio==3.12.1
python-socketio==4.5.1
pytz==2019.3
PyYAML==5.3.1
pyzmq==19.0.0
qtconsole==4.7.1
QtPy==1.9.0
regex==2020.2.20
requests==2.23.0
requests-oauthlib==1.3.0
resampy==0.2.2
rsa==4.0
scikit-learn==0.22.2.post1
scipy==1.3.2
Send2Trash==1.5.0
six==1.14.0
SoundFile==0.10.3.post1
tensorboard==2.1.1
tensorboardX==2.0
terminado==0.8.3
testpath==0.4.4
torch==1.4.0
torchsummary==1.5.1
torchvision==0.5.0
tornado==6.0.4
tqdm==4.43.0
traitlets==4.3.3
tweepy==3.8.0
unicodecsv==0.14.1
Unidecode==1.1.1
urllib3==1.25.8
wcwidth==0.1.8
webencodings==0.5.1
Werkzeug==1.0.0
widgetsnbextension==3.5.1
zipp==3.1.0
```

**Comment by EuphoriaCelestial** [comment]
https://github.com/NVIDIA/waveglow/issues/54
in this issue, they said that I can reduce parameters to increase speed, but it mean I will have to train my model again from start right?
and how exactly should I config those parameters? Can you please explain some important params in `hparams.py` file?

**Comment by Jackson-Kang** [comment]
> #54
> in this issue, they said that I can reduce parameters to increase speed, but it mean I will have to train my model again from start right?
> and how exactly should I config those parameters? Can you please explain some important params in `hparams.py` file?
> (I tried tuning those numbers before, everything are messed up)

Reducing parameters can be complicated problem, even for skillful researchers. Reducing parameters also accompanies performance degrades.

Before talking about reducing parameters, please let me know about your hardware environment. (GPU, CPU info and etc..)

**Comment by CookiePPP** [comment]
@Jackson-Kang 
>@CookiePPP can give better answer than me

I think you give me too much credit :sleepy: 
I'd like to provide parameter improvements but I haven't any major improvements that you can't find already done in the Squeezewave repo.

**Comment by Jackson-Kang** [comment]
> @Jackson-Kang
> 
> > @CookiePPP can give better answer than me
> 
> I think you give me too much credit 😪
> I'd like to provide parameter improvements but I haven't found any major improvements that you can't find already done in the [Squeezewave](https://github.com/tianrengao/SqueezeWave) repo.

Sorry, what I wanted to say is that it will be good to focus on other issues like fp32 instead of reducing parameters. If you feel that I am rude, I apologize.

**Comment by Jackson-Kang** [comment]
@EuphoriaCelestial 

FYI, Regarding reducing # of trainable parameters, I do not recommend it for inference speed improvements. Tuning network needs lots of experiments if you want to minimize the quality loss and get reasonable quality.

Think about it for saving your time.

**Comment by EuphoriaCelestial** [comment]
> > @Jackson-Kang
> > > @CookiePPP can give better answer than me
> > 
> > 
> > I think you give me too much credit sleepy
> > I'd like to provide parameter improvements but I haven't found any major improvements that you can't find already done in the [Squeezewave](https://github.com/tianrengao/SqueezeWave) repo.
> 
> Sorry, what I wanted to say is that it will be good to focus on other issues like fp32 instead of reducing parameters. If you feel that I am rude, I apologize.

I am already using fp16 in both training and inference, so I wanted to know if there is any other way to improve speed

> FYI, Regarding reducing # of trainable parameters, I do not recommend it for inference speed improvements. Tuning network needs lots of experiments if you want to minimize the quality loss and get reasonable quality.

since I am in quarantine, I have plenty of time to test. Now I only want to understand what are those parameters

**Comment by EuphoriaCelestial** [comment]
@Jackson-Kang Finally, I have re-created the echo in audio
![image](https://user-images.githubusercontent.com/43977734/81782376-e8c77080-9523-11ea-8d3c-3c892cacde02.png)

**Comment by EuphoriaCelestial** [comment]
> Sorry for late sharing.. Yesterday, I change "convert_model.py" into the codes below.
> 
> Since my model has not trained yet, I couldn't test this codes.
> Hope that this codes are helpful to you and plz let me know whether it works or not.
> 
> Explanation of code change)
> The problem is that the trained model (saved model) does not contain the number of "n_layers" Conv modules, "cond_layers", but does have one integrated Conv module with (C_in=640, C_out = n_channels * n_layers). Thus, I separate one integrated Conv module into the number of "n_layers" convolutions.
> 
> Thank you.
> 
> Changed code)
> 
> ```
> import sys
> import copy
> import torch
> 
> def _check_model_old_version(model):
>     if hasattr(model.WN[0], 'res_layers'):
>         return True
>     else:
>         return False
> 
> def update_model(old_model):
>     if not _check_model_old_version(old_model):
>         return old_model
>     new_model = copy.deepcopy(old_model)
>     for idx in range(0, len(new_model.WN)):
>         wavenet = new_model.WN[idx]
>         wavenet.res_skip_layers = torch.nn.ModuleList()
>         n_channels = wavenet.n_channels
>         n_layers = wavenet.n_layers
>         for i in range(0, n_layers):
>             if i < n_layers - 1:
>                 res_skip_channels = 2*n_channels
>             else:
>                 res_skip_channels = n_channels
>             res_skip_layer = torch.nn.Conv1d(n_channels, res_skip_channels, 1)
>             skip_layer = torch.nn.utils.remove_weight_norm(wavenet.skip_layers[i])
>             if i < n_layers - 1:
>                 res_layer = torch.nn.utils.remove_weight_norm(wavenet.res_layers[i])
>                 res_skip_layer.weight = torch.nn.Parameter(torch.cat([res_layer.weight, skip_layer.weight]))
>                 res_skip_layer.bias = torch.nn.Parameter(torch.cat([res_layer.bias, skip_layer.bias]))
>             else:
>                 res_skip_layer.weight = torch.nn.Parameter(skip_layer.weight)
>                 res_skip_layer.bias = torch.nn.Parameter(skip_layer.bias)
>             res_skip_layer = torch.nn.utils.weight_norm(res_skip_layer, name='weight')
>             wavenet.res_skip_layers.append(res_skip_layer)
>         del wavenet.res_layers
>         del wavenet.skip_layers
>     return new_model
> 
> def _check_model_trained_with_custom_data(model):
>     if hasattr(model.WN[0], 'cond_layer'):
>         return True
>     else:
>         return False
> 
> 
> def update_model_custom(old_model):
>     if not _check_model_trained_with_custom_data(old_model):
>         return old_model
> 
>     new_model = copy.deepcopy(old_model)
> 
>     for idx in range(0, len(new_model.WN)):
>         wavenet = new_model.WN[idx]
>         wavenet.cond_layers = torch.nn.ModuleList()
>         n_channels = wavenet.n_channels
>         n_layers = wavenet.n_layers
> 
>         removed_weightnorm = torch.nn.utils.remove_weight_norm(wavenet.cond_layer)
>         removed_weightnorm.weight = torch.nn.Parameter(removed_weightnorm.weight.view(n_layers, n_channels*2, 640, -1))
>         removed_weightnorm.bias = torch.nn.Parameter(removed_weightnorm.bias.view(n_layers, n_channels*2))
> 
>         print("{}".format(idx+1))
>         for cond_param_name, cond_params in removed_weightnorm.named_parameters():
> 
>             #torch.nn.utils.remove_weight_norm()
>             if cond_param_name == "bias":
>                 print("\tcond_layer_param [bias]: ", cond_params.data.size())
> 
>             else:
>                 print("\tweight norm: ", cond_param_name)
>                 print("\t\tcond_layer_params : ", cond_params.data.size())
> 
>             for i in range(0, n_layers):
>                 conv = torch.nn.Conv1d(640, n_channels*2, 1)
>                 conv.weight = torch.nn.Parameter(removed_weightnorm.weight[i])
>                 conv.bias = torch.nn.Parameter(removed_weightnorm.bias[i])
>                 print("\tconv {}-th size -  \tweight: {}\tbias: {}".format(i, conv.weight.size(), conv.bias.size()))
> 
>                 conv = torch.nn.utils.weight_norm(conv, name='weight')
>                 wavenet.cond_layers.append(conv)
> 
>         del wavenet.cond_layer
>         print("[WN END]\n\n")
> 
>     return new_model
> 
> 
> if __name__ == '__main__':
>     old_model_path = sys.argv[1]
>     new_model_path = sys.argv[2]
>     model = torch.load(old_model_path)
>     model['model'] = update_model(model['model'])
>     model['model'] = update_model_custom(model['model'])
> 
>     torch.save(model, new_model_path)
> ```

Hi @Jackson-Kang , I would like to update that your `convert_model` code work very well. I have successfully converted Waveglow pretrained model v5 to work with my Tacotron2 model, which previously only work with Waveglow v2

**Comment by Jackson-Kang** [comment]
> > > @Jackson-Kang
> > > > @CookiePPP can give better answer than me
> > > 
> > > 
> > > I think you give me too much credit sleepy
> > > I'd like to provide parameter improvements but I haven't found any major improvements that you can't find already done in the [Squeezewave](https://github.com/tianrengao/SqueezeWave) repo.
> > 
> > 
> > Sorry, what I wanted to say is that it will be good to focus on other issues like fp32 instead of reducing parameters. If you feel that I am rude, I apologize.
> 
> I am already using fp16 in both training and inference, so I wanted to know if there is any other way to improve speed
> 
> > FYI, Regarding reducing # of trainable parameters, I do not recommend it for inference speed improvements. Tuning network needs lots of experiments if you want to minimize the quality loss and get reasonable quality.
> 
> since I am in quarantine, I have plenty of time to test. Now I only want to understand what are those parameters


Hi @EuphoriaCelestial ,

I am very sorry to be late to reply. I was very busy for last 2 weeks. 
Please understand me.

How many GPU do you have?

**Comment by Jackson-Kang** [comment]
> @Jackson-Kang Finally, I have re-created the echo in audio
> ![image](https://user-images.githubusercontent.com/43977734/81782376-e8c77080-9523-11ea-8d3c-3c892cacde02.png)
> 
> it seem to happen quite often with very short input text (1-3 words)

I guess the problem is from stop linear or from the model, Tacotron 2, "assuming that the distribution of input data used to synthesis phase is similar to train phase".

In Tacotron 2, stop linear plays "kinda anomaly detector", as it predicts the end of generated mel-spcetrogram. If stop token "fires", generation will be stopped. Then, if Tacotron2 is not well -trained or generated mel-spectrogram is not reasonable, stop linear cannot be predicts well since the input of stop linear is generated mel-spectrogram(garbage-in, garbage-out).

If quality of generated audio is reasonable, I think stop token did not work, since attention alignment is nearly diagonal in the first part of speech. (but I think the your trained Tacotron2 model produces generated audio with "skipped characters".) 

If the quality of generated mel-spectrogram is not reasonable to produce understandable audio, the problem is not caused by stop-linear classifier. In this case, it is more likely that the module of mel-spectrogram generation in Tacotron2 has problem.

Unfortunately, I cannot say whether the problem is from stop-linear or Tacotron2, since more experiments must be done to identify which part is problematic and needed to fix.

**Comment by Jackson-Kang** [comment]
> > @Jackson-Kang Finally, I have re-created the echo in audio
> > ![image](https://user-images.githubusercontent.com/43977734/81782376-e8c77080-9523-11ea-8d3c-3c892cacde02.png)
> > it seem to happen quite often with very short input text (1-3 words)
> 
> I guess the problem is from stop linear or from the model, Tacotron 2, "assuming that the distribution of input data used to synthesis phase is similar to train phase".
> 
> In Tacotron 2, stop linear plays "kinda anomaly detector", as it predicts the end of generated mel-spcetrogram. If stop token "fires", generation will be stopped. Then, if Tacotron2 is not well -trained or generated mel-spectrogram is not reasonable, stop linear cannot be predicts well since the input of stop linear is generated mel-spectrogram(garbage-in, garbage-out).
> 
> If quality of generated audio is reasonable, I think stop token did not work, since attention alignment is nearly diagonal in the first part of speech. (but I think the your trained Tacotron2 model produces generated audio with "skipped characters".)
> 
> If the quality of generated mel-spectrogram is not reasonable to produce understandable audio, the problem is not caused by stop-linear classifier. In this case, it is more likely that the module of mel-spectrogram generation in Tacotron2 has problem.
> 
> Unfortunately, I cannot say whether the problem is from stop-linear or Tacotron2, since more experiments must be done to identify which part is problematic and needed to fix.

FYI, the skipping and repeating problem is quite widespread in speech synthesis task. I think this problem is not for yours, and most of researchers may experience this problem when using deep-autoregressive based model such as Tacotron, Tacotron2 and etc... Therefore, various techniques are proposed to fix this problem, and stop-linear is also one of the techniques to do so.

**Comment by Jackson-Kang** [comment]
> Hi @Jackson-Kang , I would like to update that your `convert_model` code work very well. I have successfully converted Waveglow pretrained model v5 to work with my Tacotron2 model, which previously only work with Waveglow v2

Good! I am glad, if you think my "remedy" was helpful.

But I still got a question, "did my solution really work when generating audio?"

**Comment by EuphoriaCelestial** [comment]
> How many GPU do you have?

I have PC with dual 2080ti, another with single 2080ti and a 1050ti for daily uses.

**Comment by EuphoriaCelestial** [comment]
>      
> 
> I guess the problem is from stop linear or from the model, Tacotron 2, "assuming that the distribution of input data used to synthesis phase is similar to train phase".
> 
> In Tacotron 2, stop linear plays "kinda anomaly detector", as it predicts the end of generated mel-spcetrogram. If stop token "fires", generation will be stopped. Then, if Tacotron2 is not well -trained or generated mel-spectrogram is not reasonable, stop linear cannot be predicts well since the input of stop linear is generated mel-spectrogram(garbage-in, garbage-out).
> 
> If quality of generated audio is reasonable, I think stop token did not work, since attention alignment is nearly diagonal in the first part of speech. (but I think the your trained Tacotron2 model produces generated audio with "skipped characters".)
> 
> If the quality of generated mel-spectrogram is not reasonable to produce understandable audio, the problem is not caused by stop-linear classifier. In this case, it is more likely that the module of mel-spectrogram generation in Tacotron2 has problem.
> 
> Unfortunately, I cannot say whether the problem is from stop-linear or Tacotron2, since more experiments must be done to identify which part is problematic and needed to fix.

My model give a good audio quality. I also think that Tacotron model need some kind of stop token in the input sentence, so I added "." in every input text. Most of the time, it can prevent echo, but there is still some rare cases

**Comment by Jackson-Kang** [comment]
> My model give a good audio quality. I also think that Tacotron model need some kind of stop token in the input sentence, so I added "." in every input text. Most of the time, it can prevent echo, but there is still some rare cases

Then, you have to check the text sentences in your dataset. If most of text sentences contain ".", then the model will more likely to predict the end-point of mel-sequence exactly.

**Comment by EuphoriaCelestial** [comment]
> Good! I am glad, if you think my "remedy" was helpful.
> 
> But I still got a question, "did my solution really work when generating audio?"

Yes, of course it work. After successful imported Waveglow checkpoint, I can generate audio files normally

**Comment by EuphoriaCelestial** [comment]
> > My model give a good audio quality. I also think that Tacotron model need some kind of stop token in the input sentence, so I added "." in every input text. Most of the time, it can prevent echo, but there is still some rare cases
> 
> Then, you have to check the text sentences in your dataset. If most of text sentences contain ".", then the model will more likely to predict the end-point of mel-sequence exactly.

Not all of the sentences in my training data has "." or any stop token at the end

**Comment by Jackson-Kang** [comment]
> > Good! I am glad, if you think my "remedy" was helpful.
> > But I still got a question, "did my solution really work when generating audio?"
> 
> Yes, of course it work. After successful imported Waveglow checkpoint, I can generate audio files normally

Then, I am very glad that my solution works and helpful to you. 
I was very worried if I suggest wired solution and you are got in more serious problem.

Thank you for reporting the result.

**Comment by Jackson-Kang** [comment]
> Not all of the sentences in my training data has "." or any stop token at the end

But, most of training text data contains ".", right?
If you want check that my assumption is whether correct of not, you can do several experiments.

However, you reported that this is rare case, so I think this is not serious problem.

**Comment by Jackson-Kang** [comment]
> > How many GPU do you have?
> 
> I have PC with dual 2080ti, another with single 2080ti and a 1050ti for daily uses.

I think the hyperparameter tuning and training model issues were solved. Is this topic still be worth to discuss?

**Comment by EuphoriaCelestial** [comment]
> I think the hyperparameter tuning and training model issues were solved. Is this topic still be worth to discuss?

I am still finding best value for improve inference speed, but yeah, this topic can be closed now. Many thanks to all of you for your help!
