### ISSUE TITLE
ImportError: cannot import name init_distributed

### ISSUE THREAD

**Issue by ksaidin** [NVIDIA/waveglow#199]
When I attempted to train waveglow on a single GPU Windows machine, I've got this error. `ImportError: cannot import name init_distributed`

It is solved when I remove these two lines:
[from distributed import init_distributed, apply_gradient_allreduce, reduce_tensor
from torch.utils.data.distributed import DistributedSampler](https://github.com/NVIDIA/waveglow/blob/b66c1f3ad87cf301a68a2c7a8b5492e5c625a2ea/train.py#L33)

**Comment by DDeng-Z** [comment]
Will this affect the overall process?
