### ISSUE TITLE
Reducing n_mel_channels to 40: Error of size mismatch

### ISSUE THREAD

**Issue by fatihkiralioglu** [NVIDIA/waveglow#206]
Hi, I'm trying to model a 8khz tacotron2 and waveglow model. In this scheme, I also reduce the n_mel_channels to 40.
```
"waveglow_config": {
        "n_mel_channels": 40,
        "n_flows": 12,
        "n_group": 8,
        "n_early_every": 4,
        "n_early_size": 2,
        "WN_config": {
            "n_layers": 8,
            "n_channels": 256,
            "kernel_size": 3
        }
    }
}

```

At the start of waveglow training, i got the error:
`
 RuntimeError: Given transposed=1, weight of size 40 40 1024, expected input[12, 80, 81] to have 40 channels, but got 80 channels instead`

I guess there is a place in the project where, a fixed mel size of 80 is expencted but i could not figure out where it is.

Thanks.

**Comment by CookiePPP** [comment]
https://github.com/NVIDIA/waveglow/search?q=80&unscoped_q=80

**Comment by CookiePPP** [comment]
change
https://github.com/NVIDIA/waveglow/blob/master/mel2samp.py#L70#L74

```
        self.stft = TacotronSTFT(filter_length=filter_length,
                                 hop_length=hop_length,
                                 win_length=win_length,
                                 sampling_rate=sampling_rate,
                                 mel_fmin=mel_fmin, mel_fmax=mel_fmax)
```
to include
`n_mel_channels=40`

```
        self.stft = TacotronSTFT(filter_length=filter_length,
                                 hop_length=hop_length,
                                 win_length=win_length,
                                 n_mel_channels=40,
                                 sampling_rate=sampling_rate,
                                 mel_fmin=mel_fmin, mel_fmax=mel_fmax)
```

You should also update the denoiser
https://github.com/NVIDIA/waveglow/search?q=80&unscoped_q=80

**Comment by fatihkiralioglu** [comment]
@CookiePPP, Thank you, it worked flawlesly.
