### ISSUE TITLE
not works

### ISSUE THREAD

**Issue by marshonhuckleberry** [NVIDIA/waveglow#208]
windows 10 64, python 3.8.3, latest versions of everything in requirements, not works, maybe that's for linux dont know

**Comment by EuphoriaCelestial** [comment]
yeah, if you follow the requirements.txt, I will be very surprise if it work

**Comment by marshonhuckleberry** [comment]
works after installing requirements, if you are windows user and you are new to python and github you most likely gonna fail like me, this code is designed in linux for linux. python version is not specified so i found out randomly the python version, went to pypi searched a required module, and in downloads i saw versions of that module compiled for cp36 (python36), so i figured out i need python 36 to make it work, next torch, torch cuda has to match existing cuda otherwise dll error shows up. since code is not designed for windows it means setup is not a straight forward process but trial and error,  for example tensorflow version is not specified in requirements,  installing the newest version results in errors, had to do some research to find that a version that works is 1.12, i searched a tensorflow version wich supports numpy 1.13.3 by looking in tensorflows github past versions, somewhere in tools/pip package/setup.py was supported version of numpy specified, after installing tensorflow it will update to latest numpy 1.18 i think, had to uninstall it and install 1.13.3 again, not to mention that sometimes u have to compile programs and it can take many many hours, or just simply install linux and make it all work like a glove fits on a hand, use things of how they were designed to be used and dont try to improvise, that could be a principle
