### ISSUE TITLE
Is there a way to increase speaking speed via WaveGlow Vocoder?

### ISSUE THREAD

**Issue by fatihkiralioglu** [NVIDIA/waveglow#210]
Hi,
Is it possible to change speaking rate of synthesis by tuning any parameter of Waveglow model?
Thanks.

**Comment by shwetagargade216** [comment]
you can change sampling rate and train waveglow for lower sampling rate

**Comment by Selimonder** [comment]
Try handing this on the TTS side (preferably with Glow-TTS or Flowtron). Increasing the Waveglow sample rate will indeed make changes to speaking speed but they will be rather unnatural, so it isn't highly recommended.

**Comment by rafaelvalle** [comment]
This should be handled on the text-to-spectrogram side.
