### ISSUE TITLE
Why does the Nvidia results page show contradictory results for inference?

### ISSUE THREAD

**Issue by jjoe1** [NVIDIA/waveglow#212]
This link https://devblogs.nvidia.com/generate-natural-sounding-speech-from-text-in-real-time/ says that it can synthesize upto 2.7Million audio samples/second with WaveGlow.

> Our current model synthesizes samples at 125 * 22,050 = 2,756,250, which is 125 times faster than “real-time” at 22,050 samples per second sampling rate.

But Waveglow results at the same link show throughput ranging from 40K samples/sec to 125K samples/sec, nowhere close to 2.75million. (Tacotron-2 time is minimal compared to WaveGlow, so most of the throughput time is due to Waveglow/wavenet.) 

Why is this contradiction? What is the right result about how many audio samples/sec?

> 
> Batch size | Input Length | Precision | Avg Latency (s) | Std Latency (s) | Latency Confidence Interval 50% (s) | Latency Confidence Interval 100% (s) | Throughput (samples/sec) | Avg Mels Generated (81 mels=1 sec of speech) | Avg Audio Length (s) | Avg RTF
> -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
> 1 | 128 | Mixed Precision | 3.16 | 0.13 | 3.16 | 3.81 | 48,792 | 603 | 7.00 | 2.21
> 4 | 128 | Mixed Precision | 11.45 | 0.49 | 11.39 | 14.38 | 53,771 | 601 | 6.98 | 0.61
> 1 | 128 | FP32 | 3.82 | 0.11 | 3.81 | 4.24 | 39,603 | 591 | 6.86 | 1.80
> 4 | 128 | FP32 | 13.80 | 0.45 | 13.74 | 16.09 | 43,915 | 592 | 6.87 | 0.50

**Comment by rafaelvalle** [comment]
Thank you for reporting this, @jjoe1.
We recently corrected the numbers in our README and will correct the numbers on this devblog.
The correct Waveglow speed is 55 * 22050 = 1,212,750 on naïve Pytorch FP16.

**Comment by jjoe1** [comment]
@rafaelvalle For fp32 what's the result? 

Could you also address a related issue posted at https://github.com/NVIDIA/waveglow/issues/211?

**Comment by jjoe1** [comment]
@rafaelvalle I see the update of 5*22040 for fp16 at devblogs, but shouldn't Inference Statistics table 3 and table 4 also change? 

One of the tables is posted above showing 48792,...., 43915 etc and it's unchanged.

**Comment by jjoe1** [comment]
At https://ngc.nvidia.com/catalog/resources/nvidia:tacotron_2_and_waveglow_for_pytorch/performance, one of the few results shown are these for Inference:


4 | 128 | FP32 | 4.56 | 0.12 | 4.72 | 4.77 | 4.87 | 136,518 | 1.00 | 608 | 7.06 | 1.55
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --


4 | 128 | FP32 | 14.34 | 0.42 | 14.89 | 15.08 | 15.55 | 43,489 | 1.00 | 609 | 7.07 | 0.49
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --


But the best training result for Waveglow shows under "Training performance: NVIDIA DGX-1 (8x V100 16G)" is 264,903 samples/sec for FP32, which seems better than inference. How is this possible?


8 | 10@FP16, 4@FP32 | 583,887 | 264,903 | 2.20 | 7.16 | 7.22
-- | -- | -- | -- | -- | -- | --

**Comment by rafaelvalle** [comment]
Table 3 and Table 4 are correct.
Remember that WaveGlow's current optimal speed is 55 * 22050 = 1,212,750 on naïve Pytorch FP16 on a V100 with a a single batch tensor of dimensions (1, 80, 880), i.e. approximately 10 seconds.

**Comment by jjoe1** [comment]
@rafaelvalle Do you mean table-3 and 4 are correct because they measure tacotron-2+waveglow result and so some difference is expected? But as we know Waveglow is much much more computationally heavy and a bottleneck in tacotron-2+WaveGlow end-to-end, I would have expected that the difference should not be ~25X (55*22050 versus first-row in table-4 with value 48,792 samples/sec which is about 25X less).


Also, in the end-to-end tacotron-2 + Waveglow work, is there a maximum input-text length requirement? E.g. when tacotron-2 inference processes input text to generate their mel-spectrums, can one input say sentences of length 5000 or 1000 characters as input-text along with sentences of length 50 chars and it'd generate mel-frames for all of them equally well, or are there some specific limit on input-text as it's processed by a bi-directional encoder within tacotron-2?

**Comment by rafaelvalle** [comment]
Table 3 and 4 are correct because the code used to compute them is correct.
Unless you implement a streaming version of Tacotron 2 + Waveglow, the length of the input text will be memory bound.
One can also split the text according to punctuation.

**Comment by jjoe1** [comment]
> Tacotron 2 + Waveglow, the length of the input text will be memory bound.

Does "memory-bound" here mean that for very long input-text (say 10000 chars) it'd still generate the whole mel-spectrum but the inefficiently, or not generate at-all if memory requirement for some memory-heavy layer like Attention isn't met? It's unclear because the max_iters hyperpram specifies the max_frames it can generate by the decoder, but there isn't anything for input-text so hugely long input-text and short input-text may have both equal number of output frames.

> Table 3 and 4 are correct because the code used to compute them is correct.
but how does it align with the 25X difference point raised earlier. Just adding tacotron-2 made it 25X slower seems unexpected?

**Comment by rafaelvalle** [comment]
"memory-bound" is equivalent to run out of memory.
The [max_decoder_steps](https://github.com/NVIDIA/tacotron2/blob/master/hparams.py#L59) is a hard-stop gate in case the model's own gate does not work.

Tacotron 2 is around 7x faster than real-time, considerably slower than Waveglow.

**Comment by jjoe1** [comment]
> Tacotron 2 + Waveglow, the length of the input text will be memory bound.

Sorry I don't follow, want to check if I'm missing something.

Does it mean the model itself doesn't have any limitation regarding input-text/sentence length (without splitting) to which all text that is to be converted to speech needs to be truncated to or padded till? That is, it could even generate speech for 1 million character long text fed to the bi-directional encoder-layer of tacotron-2?

**Comment by CookiePPP** [comment]
@jjoe1 
Aye. Length limitation is mainly cause the attention mechanism uses key-query which struggles with too many inputs. Given enough capacity or [another attention mechanism](https://arxiv.org/abs/1910.10288) and infinite VRAM, Tacotron2 can generate 1 million char long texts.
