### ISSUE TITLE
About versions of published models

### ISSUE THREAD

**Issue by chychen** [NVIDIA/waveglow#213]
what is the difference between different versions of models?
such as **waveglow_256channels_universal_v3** and **waveglow_256channels_universal_v5**.

(sorry to ask such a tiny problem.
thanks

**Comment by rafaelvalle** [comment]
The difference between `waveglow_256channels_universal_v4` and  `waveglow_256channels_universal_v5` is that `v5` converts `v4` to be compatible with the new code.
