### ISSUE TITLE
use .npy file to get the audio

### ISSUE THREAD

**Issue by YihWenWang** [NVIDIA/waveglow#214]
I had trained the Multilingual Tacotron2 instead of Tacotron2 of nvidia.
When I run this Multilingual Tacotron2 model, I get the npy output for the mel-spectrogram.
I load this .npy file and try to use waveglow to get the audio.
But the result is noise.
I plot its mel-spectrogram like this figure, it looks like no problem.
![12235295496817](https://user-images.githubusercontent.com/19651566/86120434-e1294e80-bb06-11ea-8af4-30165cc533bc.png)
So I don't have any idea how do I use the .npy file to get the synthesized audio from waveglow?

**Comment by rafaelvalle** [comment]
Confirm that the mel-configuration used for Waveglow and your Tacotron match.
Confirm that the input tensor has the expect shape Waveglow expects.

**Comment by YihWenWang** [comment]
![plot_1](https://user-images.githubusercontent.com/19651566/86216220-48e7a400-bbb0-11ea-979a-d593f0548dc6.png)
The left spectrogram is from waveglow.
The right spectrogram is from my tacotron2, and it had done "trim silence" from librosa.
The left could be synthesized audio by waveglow, but the right didn't.
I don't understand it.

**Comment by gbaian10** [comment]
@YihWenWang I have the same problem, have you solved it?

**Comment by YihWenWang** [comment]
> @YihWenWang I have the same problem, have you solved it?

Yes, I have solved it.

**Comment by matko123** [comment]
@YihWenWang same problems here, could you please tell which parts of the code did you change to make it work? Thanks in advance.

**Comment by YihWenWang** [comment]
> @YihWenWang same problems here, could you please tell which parts of the code did you change to make it work? Thanks in advance.

**Comment by YihWenWang** [comment]
@matko123 
Hi!
Please check the code for extracting the Mel-spectrogram, you must make them the same.
For example, your synthesizer and your vocoder for the way of extracting the Mel-spectrogram must be the same.
