### ISSUE TITLE
Does waveglow model the spectrum magnitude only?

### ISSUE THREAD

**Issue by philippaichinger** [NVIDIA/waveglow#225]
Hello everybody,
I am comparing input to output wavs. What I see is good agreement in terms of magnitude spectrograms, but a significant mismatch in the time-domain. Is it possible that waveglow only models the magnitude spectrogram while neglecting the phase? This is what I would have understood from using the 80-mel channels spectrograms as intermediate representations of speech samples.
Kind regards, Philipp Aichinger

**Comment by rafaelvalle** [comment]
Waveglow learns an invertible mapping, between the audio distribution and a gaussian distribution, conditioned on mel spectrograms. This implies that WaveGlows models only the phase directly and the magnitude indirectly through the audio itself.

**Comment by philippaichinger** [comment]
thank you
