### ISSUE TITLE
Is the published model trained only on LJSpeech?

### ISSUE THREAD

**Issue by MuyangDu** [NVIDIA/waveglow#234]
Is the published pretrained model trained only on LJSpeech? The filename of the published model contains 'universal' so I'm wondering if any other data besides LJSpeech was used to train. Thanks

**Comment by meenalmalik** [comment]
The model is trained just on LJ speech dataset. But you can surely alter/customize the length of the training and test files, by following the "train your own model" guide:)

**Comment by MuyangDu** [comment]
> The model is trained just on LJ speech dataset. But you can surely alter/customize the length of the training and test files, by following the "train your own model" guide:)

Thanks for the explanation.
