### ISSUE TITLE
 get out of memory error

### ISSUE THREAD

**Issue by Hayes515** [NVIDIA/waveglow#24]
Hi, I have changed batch_size to 1, when I run "python train.py -c config.json", I still got error below.
 
![default](https://user-images.githubusercontent.com/29434347/48467854-1c3d1800-e825-11e8-8007-cfe997d3738f.png)

GPU:
![default](https://user-images.githubusercontent.com/29434347/48468130-fe23e780-e825-11e8-89cb-1339632c3a61.png)

Can you help me or give some advices?

**Comment by belevtsoff** [comment]
try decreasing the segment length in the config

**Comment by yhgon** [comment]
decrease batch size first 3to 2 or 1

**Comment by Hayes515** [comment]
@belevtsoff  it works, thanks
