### ISSUE TITLE
RuntimeError: A tensor was not contiguous.

### ISSUE THREAD

**Issue by sciai-ai** [NVIDIA/waveglow#248]
Hi

I ran the train script and got the following 

python train.py -c config.json

![image](https://user-images.githubusercontent.com/52277510/109405816-59565580-79af-11eb-8aec-b684f0309fff.png)

**Comment by Selimonder** [comment]
This issue might have been caused by nvidia's apex. You can either disable the fp16 run from config or alternatively you can replace apex with torch native mixed-precision training.

**Comment by bfs18** [comment]
change L79 in glow.py to 
```
        W = W.contiguous().view(c, c, 1)
```
