### ISSUE TITLE
4 whistling frequencies

### ISSUE THREAD

**Issue by innarid** [NVIDIA/waveglow#249]
I noticed that after inferring waveglow on zero audio (https://github.com/NVIDIA/waveglow/blob/master/denoiser.py#L30) I get 4 whistling frequencies
![zero_204](https://user-images.githubusercontent.com/28152130/110788473-b7bce700-827f-11eb-954d-92829ddc082c.png)
So I have anomalies in synthetic audios (frequencies 0, 2756.25, 5512.5, 8268.75, 11025 with sample rate 22050)
![bel](https://user-images.githubusercontent.com/28152130/110803296-19854d00-8290-11eb-8bb0-9666c7455d3e.png)
Does anybody know what is the reason of this effect?

**Comment by adrianastan** [comment]
https://github.com/NVIDIA/tacotron2/issues/142#issuecomment-466506044

**Comment by innarid** [comment]
@adrianastan  Thanks! But why are there 4 frequencies? Can I change the number of these frequencies?

**Comment by innarid** [comment]
I found the reason. It's spectrogram scliceing along frequency axis in Wavenet architecture 
https://github.com/NVIDIA/waveglow/blob/master/glow.py#L165
