### ISSUE TITLE
120k, the generate wav is not good

### ISSUE THREAD

**Issue by hdmjdp** [NVIDIA/waveglow#30]
how many steps do you got clear wav without noise?

**Comment by hdmjdp** [comment]
[

](url)

**Comment by rafaelvalle** [comment]
Please check issue https://github.com/NVIDIA/waveglow/issues/12

**Comment by hdmjdp** [comment]
@rafaelvalle I have check it, but It think their result is not good. Does this model just so so?

**Comment by hdmjdp** [comment]
@rafaelvalle can I reopen this issue?

**Comment by rafaelvalle** [comment]
Let's carry on this discussion here https://github.com/NVIDIA/waveglow/issues/12.
