### ISSUE TITLE
pip install requirements fail = pytorch not yet available

### ISSUE THREAD

**Issue by xkunglu** [NVIDIA/waveglow#36]
For all I know, as of today 1.0 isn't yet out  in pip. 

$ pip install -r requirements.txt 
Collecting torch==1.0.0a0 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement torch==1.0.0a0 (from -r requirements.txt (line 1)) (from versions: 0.1.2, 0.1.2.post1, 0.3.1, 0.4.0, 0.4.1)
No matching distribution found for torch==1.0.0a0 (from -r requirements.txt (line 1))

**Comment by rafaelvalle** [comment]
Thank you. 
We updated the readme and the requirements.txt file.
