### ISSUE TITLE
Coupling layer loss computation

### ISSUE THREAD

**Issue by sharvil** [NVIDIA/waveglow#37]
It looks like the coupling layer loss is first summed over all batches, time steps, and channels (https://github.com/NVIDIA/waveglow/blob/master/glow.py#L55). Note that the number of channels for all coupling layers is not fixed due to early outputs reducing the channel count. But then the loss is averaged over batches, time steps, and n_group (https://github.com/NVIDIA/waveglow/blob/master/glow.py#L59). This means that regardless of the number of channels actually present in a given coupling layer, we're averaging over n_group (8).

Is this intentional? It's unclear to me why the coupling layer loss is computed this way.

**Comment by rafaelvalle** [comment]
Closing in favor of [issue](https://github.com/NVIDIA/waveglow/issues/37)
