### ISSUE TITLE
Generated results sounds speaking with echo.

### ISSUE THREAD

**Issue by chaiyujin** [NVIDIA/waveglow#41]
Train model with batch size 4 for 80k steps. The generated samples sounds like [this](https://soundcloud.com/nlbhyn05favu/waveglow-80k). It sounds like echo.

I want to know if I train the model further, can I get better results?

**Comment by chaiyujin** [comment]
Better results after further training

**Comment by Yeongtae** [comment]
could you share your final audio samples?
