### ISSUE TITLE
RuntimeError: DataLoader worker is killed by signal: Illegal instruction.

### ISSUE THREAD

**Issue by shardullavekar** [NVIDIA/waveglow#44]
I am using PyTorch 1.0.0a0+1e05f4b

Here's the output of nvidia-smi:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   39C    P0    27W / 300W |      0MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**When I run train.py, I get  RuntimeError: DataLoader worker is killed by signal: Illegal instruction.**

I tried increasing shared memory following [this link](https://www.lucidarme.me/increase-shared-memory-limit/). But didn't help.

Here's the full stack trace. 

Traceback (most recent call last):
  File "train.py", line 171, in <module>
    train(num_gpus, args.rank, args.group_name, **train_config)
  File "train.py", line 110, in train
    for i, batch in enumerate(train_loader):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 632, in __next__
    idx, batch = self._get_batch()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 611, in _get_batch
    return self.data_queue.get()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 274, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 13993) is killed by signal: Illegal instruction.

**Comment by rafaelvalle** [comment]
Try decreasing the batch size and see if the error persists.

**Comment by shardullavekar** [comment]
Hey, the batch size is already 1 (reduced it to 1 from 3) Still the error persists.

**Comment by shardullavekar** [comment]
Hey, the batch size is already 1 - I already tried that. Still the same.

**Comment by rafaelvalle** [comment]
Try a smaller architecture, e.g. less residual channels.
I'm suggesting these changes because I believe the error is an un-catched out of memory.

**Comment by Ella77** [comment]
https://github.com/NVIDIA/apex/issues/317#issuecomment-494463956 Change either Pytorch or Cuda version that can be matched !
