### ISSUE TITLE
About fp16 error

### ISSUE THREAD

**Issue by hdmjdp** [NVIDIA/waveglow#45]
File "train.py", line 144, in train
    loss.backward()
  File "/tmp/venv3/lib64/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/tmp/venv3/lib64/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/running_package/waveglow-fp16/distributed.py", line 125, in allreduce_params
    coalesced = _flatten_dense_tensors(grads)
  File "/running_package/waveglow-fp16/distributed.py", line 68, in _flatten_dense_tensors
    flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0)
RuntimeError: Expected a Tensor of type torch.cuda.HalfTensor but found a type torch.cuda.FloatTensor for sequence element 926 in sequence argument at position #1 'tensors'

**Comment by hdmjdp** [comment]
@rafaelvalle I just fix the code according to your inference code. Now it can train except inconv.

**Comment by hdmjdp** [comment]
@rafaelvalle step0's model size is 1.93G,  but in step>0, the mode size is still 3.93G, what is wrong?

**Comment by rafaelvalle** [comment]
The difference between step 0 and step > 0 probably comes from the optimizer state.

**Comment by rafaelvalle** [comment]
please create a new issue if you have a problem different from the header in this issue.

**Comment by rafaelvalle** [comment]
This is not a problem.

**Comment by viig99** [comment]
@hdmjdp are you getting good results with fp16 training ? besides making the changes from the inference code onto training, were there any other changes that you needed to make?

**Comment by hdmjdp** [comment]
@viig99 No need to make changes of infer code.

**Comment by rafaelvalle** [comment]
@hdmjdp did you train the model with fp16 and if you did can you share samples?

**Comment by farzanehnakhaee70** [comment]
Is there any update for this issue?
