### ISSUE TITLE
It is not clear how to generate wav files from text directly.

### ISSUE THREAD

**Issue by ahmetaa** [NVIDIA/waveglow#46]
In the readme file, for generating wav files, mel-spectrograms seems to be necessary. Why so? How can I generate wav outputs directly from arbitrary text data?

**Comment by xingjy10** [comment]
@yhgon

**Comment by nanma** [comment]
@ahmetaa Waveglow(WaveNet, ClariNet, etc) serves as a vocoder whose purpose is to transform mel-spectrogram to audio.
For generating mel-spectrograms from text, you could use [Nvidia's tacotron2](https://github.com/NVIDIA/tacotron2). 
A fully end2end model of generating wav from text without a vocoder is a very difficult task, I don't think there exists such model currently.

**Comment by nanma** [comment]
@xingjy10 You can use code below to save mel-spectrogram from Nvidia's tacotron2 as file, and pass the file to Waveglow to generate wav.
`torch.save(mel_outputs_postnet[0], './demo.pt')`

**Comment by ahmetaa** [comment]
@nanma Thanks for the explanation.

**Comment by rafaelvalle** [comment]
Yes, please take a look at our tacotron 2 implemenation. We provide an inference demo that combines tacotron 2 and waveglow.
https://github.com/NVIDIA/tacotron2

**Comment by Mr-DDDAlKilanny** [comment]
When training, I think we need to train both waveglow and tacotron, right?
