### ISSUE TITLE
@torch.jit.script is not working properly 

### ISSUE THREAD

**Issue by zceehua** [NVIDIA/waveglow#47]
Torch version is: 0.4.1(the lastest version shown in official website)
CUDA: 8.0
CUDNN: 7.0

I have no idea about the error and my colleague came with the same problem.

Here is the log:
raise NotSupportedError(base.range(), "slicing multiple dimensions at the same time isn't supported yet")
torch.jit.frontend.NotSupportedError: slicing multiple dimensions at the same time isn't supported yet
@torch.jit.script
def fused_add_tanh_sigmoid_multiply(input_a, input_b,n_channels):
  n_channels_int = n_channels[0]
  in_act = input_a+input_b
  t_act = torch.nn.functional.tanh(in_act[:, :n_channels_int, :])
<--- HERE
  s_act = torch.nn.functional.sigmoid(in_act[:,n_channels_int:, :])
  acts = t_act * s_act
  return acts

**Comment by yhgon** [comment]
https://github.com/NVIDIA/waveglow/issues/4#issuecomment-441032996 
it's pytorch version issue. if you update pytorch 1.0.0a0, it works well.

**Comment by jiqizaisikao** [comment]
I removed all the @torch.jit.script and it works well for pytorch of version 0.4

**Comment by rafaelvalle** [comment]
Please update to pytorch 1.0 to benefit from the performance improvement.

**Comment by zceehua** [comment]
@jiqizaisikao  Awesome! That works, thanks man!

**Comment by jiangyangbo** [comment]
@jiqizaisikao ， @zceehua ，  i removed @@torch.jit.script , and pytorch of version is 0.4, but result a error: AttributeError: Can't get attribute '_rebuild_parameter' on <module 'torch._utils' from '/home/greed/anaconda3/lib/python3.6/site-packages/torch/_utils.py'>

**Comment by rafaelvalle** [comment]
Please update to pytorch 1.0.

**Comment by jiangyangbo** [comment]
@rafaelvalle  , I update to pytorch 1.0,  it work well now. Tks.

**Comment by Diaislam** [comment]
well i had pytorch 1.0 installed and i had to downgrade it to solve an error so i can't upgrade it again
