### ISSUE TITLE
Set WN channel nums smaller

### ISSUE THREAD

**Issue by jiqizaisikao** [NVIDIA/waveglow#48]
Hi,the original model is too big for most people too train on single GPU,but if we set WN channel num smaller such like 256,we can train it for larger batch size on single GPU,is the last speech quality  the same?

**Comment by rafaelvalle** [comment]
We haven't done such ablation studies.
One can reduce the number of residual channels and increase the number of flows.

**Comment by rafaelvalle** [comment]
We've started doing ablation studies and it looks like using 256 channels produces good results as well.
