### ISSUE TITLE
about n_group

### ISSUE THREAD

**Issue by hdmjdp** [NVIDIA/waveglow#50]
has anyone change the n_group to 4 instead of 8?
I just want to remove the line noise. if n_group=4, for 24k audio, the line noise only exist in 6k and 12k. but I can not change it, it will give error:

  File "/running_package/waveglow/glow.py", line 231, in forward
    output = self.WN[k]((audio_0, spect))
  File "/tmp/venv3/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/running_package/waveglow/glow.py", line 145, in forward
    audio = self.start(audio)
  File "/tmp/venv3/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/tmp/venv3/lib64/python3.6/site-packages/torch/nn/modules/conv.py", line 176, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [512, 2, 1], expected input[3, 1, 1500] to have 2 channels, but got 1 channels instead

this is the config:

    "waveglow_config": {
        "n_mel_channels": 80,
        "n_flows": 6
        "n_group": 4,
        "n_early_every": 2,
        "n_early_size": 1,
        "WN_config": {
            "n_layers": 8,
            "n_channels": 512,
            "kernel_size": 3

**Comment by hdmjdp** [comment]
@yoyololicon 
int(self.n_early_size/2)， there is int（）
 why must even？

**Comment by hdmjdp** [comment]
@yoyololicon if i change n_early_size to 2, I got another error:

   train(num_gpus, args.rank, args.group_name, **train_config)
  File "train.py", line 75, in train
    model = WaveGlow(**waveglow_config).cuda()
  File "/running_package/waveglow/glow.py", line 194, in __init__
    self.convinv.append(Invertible1x1Conv(n_remaining_channels))
  File "/running_package/waveglow/glow.py", line 60, in __init__
    bias=False)
  File "/tmp/venv3/lib64/python3.6/site-packages/torch/nn/modules/conv.py", line 172, in __init__
    False, _single(0), groups, bias)
  File "/tmp/venv3/lib64/python3.6/site-packages/torch/nn/modules/conv.py", line 38, in __init__
    self.reset_parameters()
  File "/tmp/venv3/lib64/python3.6/site-packages/torch/nn/modules/conv.py", line 44, in reset_parameters
    stdv = 1. / math.sqrt(n)
ZeroDivisionError: float division by zero

**Comment by yoyololicon** [comment]
Because n_half will not match with n_remaining_channels.
In your case at the begining, your n_half = 2.
Because int(1/2) = 0, after this line the n_half won't change.
https://github.com/NVIDIA/waveglow/blob/6c6d5fcce1351203c2029dcf0fefd06f5647b948/glow.py#L201
but n_remaining_channles will minus 1.
https://github.com/NVIDIA/waveglow/blob/6c6d5fcce1351203c2029dcf0fefd06f5647b948/glow.py#L202

The WN() is constructed by n_half value (which will always be 2 in your case), so after the first early output operation, audio.size(1) should be 3, and 3 cannot divided by 2, so only the first channel is send to WN[k]. But it expected to have 2 channels as input.

**Comment by yoyololicon** [comment]
> @yoyololicon if i change n_early_size to 2, I got another error:
> 
> train(num_gpus, args.rank, args.group_name, **train_config)
> File "train.py", line 75, in train
> model = WaveGlow(**waveglow_config).cuda()
> File "/running_package/waveglow/glow.py", line 194, in **init**
> self.convinv.append(Invertible1x1Conv(n_remaining_channels))
> File "/running_package/waveglow/glow.py", line 60, in **init**
> bias=False)
> File "/tmp/venv3/lib64/python3.6/site-packages/torch/nn/modules/conv.py", line 172, in **init**
> False, _single(0), groups, bias)
> File "/tmp/venv3/lib64/python3.6/site-packages/torch/nn/modules/conv.py", line 38, in **init**
> self.reset_parameters()
> File "/tmp/venv3/lib64/python3.6/site-packages/torch/nn/modules/conv.py", line 44, in reset_parameters
> stdv = 1. / math.sqrt(n)
> ZeroDivisionError: float division by zero

Because you have 6 flows, so it will have 2 early output operations.
But after the second early output operation, your n_remaining_channels is 0, so you can't construct a convolution layer.
Increase n_flows or n_early_every.

**Comment by hdmjdp** [comment]
@yoyololicon thanks, if i use this config, can i got right answer:

    "waveglow_config": {
        "n_mel_channels": 80,
        "n_flows": 6,
        "n_group": 4,
        "n_early_every": 3,
        "n_early_size": 2,
        "WN_config": {
            "n_layers": 8,
            "n_channels": 512,
            "kernel_size": 3
        }

**Comment by mataym** [comment]
> @yoyololicon thanks, it work now.

hi @hdmjdp , how did u solve this problem? i have a same error, my waveglow_config is as follows:
"waveglow_config": {
        "n_mel_channels": 80,
        "n_flows": 12,
        "n_group": 8,
        "n_early_every": 4,
        "n_early_size": 2,
        "WN_config": {
            "n_layers": 8,
            "n_channels": 256,
            "kernel_size": 3
        }
    }
i did not use pretrained waveglow model, i trained the model from scratch with my own data. can u tell me how to solve it? thanks!
