### ISSUE TITLE
Segment size, batch size and VRAM; fp16

### ISSUE THREAD

**Issue by Worldexe** [NVIDIA/waveglow#52]
Can somebody please share train config and other parameters for training on LJ data (22kHz) on 1080 (8Gb mem) card?
I am trying to use default config as in current master and getting out-of-video-memory errors.

I have already lowered batch_size to 1 and tried to reduce segment_size, but that did not help. 

Also, I do not see any train options to switch to fp16; although they are in inference script.

**Comment by triwoods** [comment]
I have one 1080Ti (11 Gb memory), with batch size of 1, it barely fits the model with default configuration. If yours is 1080, I guess other than using batch size of 1, you have to reduce the model size as well. You probably want to reduce the "n_channels" in WN_config (512 -> 256), but you might see some performance degradation. It will be a trade-off.

**Comment by Worldexe** [comment]
Was able to fit it into 8Gb VRAM by lowering "n_layers": from 8 to 7. Of course, it will likely reduce model quality, but still.

So, on 8x 1080 I was able to get some quality after 20hours of trainig - It has severe artifacts, but I can understand whats said.

**Comment by rafaelvalle** [comment]
Try reducing the number of channels from 512 to 256.
