### ISSUE TITLE
CPU inference?

### ISSUE THREAD

**Issue by Worldexe** [NVIDIA/waveglow#53]
How can I run inference in CPU-only device? Removing `cuda()` in `inference.py`  and adding map to cpu on model load does not help - it still asks for GPU:
```
Traceback (most recent call last):
  File "inference.py", line 73, in <module>
    args.output_dir, args.sampling_rate, args.is_fp16)
  File "inference.py", line 46, in main
    mel = torch.autograd.Variable(mel.cuda())
  File "/home/ttsynth/tacotron2-nvidia-new/tacotron2/p3.6_venv/lib/python3.6/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    _check_driver()
  File "/home/ttsynth/tacotron2-nvidia-new/tacotron2/p3.6_venv/lib/python3.6/site-packages/torch/cuda/__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

**Comment by rafaelvalle** [comment]
Yes, you will need to manually remove the .cuda() calls in the model. code.
Please note that that you need a GPU to benefit from faster than real-time inference.

**Comment by nashannashui** [comment]
cpu inference is slow than real-time?

**Comment by yoyololicon** [comment]
Yes. It's actually pretty slow.

**Comment by xxoospring** [comment]
> Yes. It's actually pretty slow.

what's means "pretty slow"? how long it will take like the sentence: "hello, I'm Jack. "

**Comment by yoyololicon** [comment]
In my experience probably more than one to a few minutes.

> > Yes. It's actually pretty slow.
> 
> what's means "pretty slow"? how long it will take like the sentence: "hello, I'm Jack. "

In my experience probably more than one to a few minutes.
