### ISSUE TITLE
what brings the improvement of inference speed from 1200khz to 2750khz?

### ISSUE THREAD

**Issue by wenyong-h** [NVIDIA/waveglow#57]
The recent commit https://github.com/NVIDIA/waveglow/commit/f70678e798df7961dd7f929285f04769eae0fdc0 claims a big improvement of inference speed.
But there was no code change, so i am wondering what brings the improvement.

**Comment by yoyololicon** [comment]
Maybe the support of FP16 ?

**Comment by rafaelvalle** [comment]
Reducing the number of channels from 512 to 256 and still maintaining audio quality.

**Comment by hdmjdp** [comment]
@rafaelvalle have your try to reduce the WN layers(n_layers) from 8 to 4?

**Comment by rafaelvalle** [comment]
No, we have not.

**Comment by TomGledhill** [comment]
Hello @rafaelvalle! Thank you all, for this awesome project! 
Could you please share pretrained weights of model with reduced number of channels? 
Thanks in advance!

**Comment by tugstugi** [comment]
@rafaelvalle I second @TomGledhill is it possible to share the model with 256 channels?

**Comment by rafaelvalle** [comment]
https://drive.google.com/open?id=1WsibBTsuRg_SF2Z6L6NFRTT-NjEy1oTx
