### ISSUE TITLE
Mu_law quantization 

### ISSUE THREAD

**Issue by yhgon** [NVIDIA/waveglow#61]
Plz add mu_law quantization option same as nv-wavenet. 
[Nv_Wavenet](https://github.com/NVIDIA/nv-wavenet/blob/master/pytorch/mel2samp_onehot.py#L90)
[Nv-wavenet util](https://github.com/NVIDIA/nv-wavenet/blob/master/pytorch/utils.py#L62)

**Comment by rafaelvalle** [comment]
Our goal is to keep the repo as clean and simple as possible.

**Comment by Yeongtae** [comment]
@yhgon 
Have you tried the test?
Does mu-law make a performance improvement?
