### ISSUE TITLE
RuntimeError: MAGMA getri : U(1,1) is 0, U is singular

### ISSUE THREAD

**Issue by nanma** [NVIDIA/waveglow#63]
During training, I met this error after some epochs:
```
...
375717: -6.074426174
375718: -6.012949944
375719: -6.116100311 
Traceback (most recent call last):
  File "train.py", line 176, in <module>
    train(num_gpus, args.rank, args.group_name, **train_config)
  File "train.py", line 126, in train
    loss.backward()
  File "/home/research/tts/pytorch-env/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/research/tts/pytorch-env/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: MAGMA getri : U(1,1) is 0, U is singular at /pytorch/aten/src/THC/generic/THCTensorMathMagma.cu:451
```

If I resume training, this error occurs again after some epochs.  My pytorch version is `1.0.0.dev20181127`.
I did some search but found nothing related, is there any clue for this problem?

**Comment by rafaelvalle** [comment]
That's probably not a problem with PyTorch.
A matrix is singular if its determinant is zero, in which case it has no inverse.
WaveGlow loss functions rewards an increase in determinant, so it's surprising that your hitting zero determinants.

What's your training setup?

**Comment by rafaelvalle** [comment]
How large is your dataset?

**Comment by nanma** [comment]
I use the LJ Speech data according to readme.

**Comment by rafaelvalle** [comment]
The models we shared were trained on LJS with the hyperparameters in this github repo.
Look closely at the modifications you have made. I think that reducing the batch size should not lead to that error.

**Comment by orionpeng** [comment]
@nanma I met the same problem too. I guess you should use another version of CUDA and Cudnn. Because when I updated the CUDA and Cudnn, this never happens.

**Comment by nanma** [comment]
@orionpeng I think you're right. I do the training on another machine with different version of CuDNN，the error doesn't occur. Thanks for your suggestion.
