### ISSUE TITLE
Removing the conditioning on mel-spectrogram

### ISSUE THREAD

**Issue by fakufaku** [NVIDIA/waveglow#64]
Hi, first of all thanks for sharing the model and the code. This is really interesting work and very useful!

I would like to use waveglow as a generative model in some other maximum likelihood setting. In my setting, the clean mel spectrogram is not available, but I still want to evaluate the likelihood of a signal.

I have currently removed the conditioning on the mel-spectrogram and am re-training the model on a dataset with a larger number of speakers (WSJ0 dataset). The training is doing the 10th epoch and there are around 70000 speech segments in the dataset. 

1. Do you think the network should still train correctly without any conditioning ?

2. I've been training a little over a week now with 5 GPUs and the samples have some voice like characteristics, but are very noisy. Do you think just continuing training will alleviate this, or should I consider a different approach ? I've put a couple of [samples on google drive](https://drive.google.com/drive/folders/1z_JGIUP2rhs91zTOt_cqrAro1Y560UsY?usp=sharing). One is with `sigma=1` and the other `sigma=1.15`. 

3. Were I to add back the mel spectrogram layer, is it possible to run back-prop through it ? In that case, I would just compute the mel-spec of my input signal and feed it together to the model.

Thanks for the help!

**Comment by fakufaku** [comment]
Ping @rafaelvalle

**Comment by rafaelvalle** [comment]
1) During inference the signal output will be completely conditioned on the random normal vector z. if the signal is speech, my guess is that the output will be babble, just like wavenet without mel conditioning.

2. Lower sigma will decrease the variance of the output and this will reduce noise. We've also noticed that training for longer does help.

3. Yes, it will require some model "surgery: add the cond_layer for the fused_add_tanh_sigmoid_multiply and resume training the model.

**Comment by fakufaku** [comment]
Thank you very much for the answer! I have been training a somewhat reduced model that doesn't use the conditioning for a few weeks now. I am indeed getting some babble when doing inference, however it is pretty noisy still.
Is it possible the conditioning on mel-spec helps reduce the noise significantly ?
I haven't tried 3. yet. I might give it a try soon, and will report how it works.

**Comment by rafaelvalle** [comment]
I assume that better conditioning can reduce the entropy in the output and, hence, decreasing the noise that, as I understand, comes from high entropy.
