### ISSUE TITLE
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:511

### ISSUE THREAD

**Issue by hubeibei007** [NVIDIA/waveglow#66]
When I train the model, there is an error occured at glow.py line 100, the operation torch.logdet(W). The following is the error info. My env is python3.5 and pytorch 1.0.0.  I'm not sure if it is a pytorch version problem. Is there any clue for this problem? 

# CUDA_VISIBLE_DEVICES=2 python train.py  -c config.json
output directory checkpoints
Epoch: 0
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument
Traceback (most recent call last):
  File "train.py", line 173, in <module>
    train(num_gpus, args.rank, args.group_name, **train_config)
  File "train.py", line 118, in train
    outputs = model((mel, audio))
  File "/data/waveglow/venv_waveglow/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/waveglow/glow.py", line 233, in forward
    audio, log_det_W = self.convinv[k](audio)
  File "/data/waveglow/venv_waveglow/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/waveglow/glow.py", line 100, in forward
    log_det_W = batch_size * n_of_groups * torch.logdet(W)
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:511

**Comment by hubeibei007** [comment]
The mismatch between the driver version and cuda version lead to this problem.

**Comment by qnkhuat** [comment]
which driver and cuda version are u using ? @hubeibei007

**Comment by Jeevesh8** [comment]
I get the error on Colab. And I didn't installed any PyTorch or CUDA component.
