### ISSUE TITLE
is it important normalization of the audio values?

### ISSUE THREAD

**Issue by Yeongtae** [NVIDIA/waveglow#71]
my audio dataset has low amplitude values.
In int16, [-3500, 3500] = [0.1 x min_int16,  0.1 x max_int16]
In float32, [-0.1, 0.1].

Is it affects the quality of the synthesized result?

Though my model reached to 1000 epoch, the synthesized result is unstable.
[1.zip](https://github.com/NVIDIA/waveglow/files/2748826/1.zip)

**Comment by Yeongtae** [comment]
After doing normalize audio amplitudes, My model have take training with 100 epochs.
But it is still unstable compare with wavenet(https://github.com/Rayhane-mamah/Tacotron-2).
It only affect final amplitude of sound.
[2.zip](https://github.com/NVIDIA/waveglow/files/2754652/2.zip)

**Comment by truemanlee** [comment]
What the value of sigma did you use when inferred? Your wav file sounds noisy. A smaller value of sigma may do help.

**Comment by Yeongtae** [comment]
Sqrt(0.5) for trainning.
0.66 for inference.

**Comment by yxt132** [comment]
do you mean normalizing mel-spectrogram or original audio wav?

**Comment by Yeongtae** [comment]
@yxt132 Original aduio wav

**Comment by acrosson** [comment]
@Yeongtae how did you normalize your audio? did you use something like `ffmpeg-normalize`? And what range did you normalize to?

**Comment by Yeongtae** [comment]
> @Yeongtae how did you normalize your audio? did you use something like `ffmpeg-normalize`? And what range did you normalize to?

- I don't know ffmpeg-normalize, so I can't compare.
- log melspectrogram to  [-4, 4]

**Comment by m-toman** [comment]
Don't know if you're still on that @Yeongtae but I'm experiencing similar issues that the scaling
audio/abs(audio).max() *0.99
leads to loss explosion and a much higher loss in general. 

The more I go down to something like 0.4 the lower the loss is. 
At first I thought it's just a scaling thing between those runs and does not correlate to perception. But in fact the larger the range of the wav amplitude is, the worse the training behaves.
