### ISSUE TITLE
about WaveGlow parameters

### ISSUE THREAD

**Issue by caicaibins** [NVIDIA/waveglow#76]
@all
HI，
   In class WaveGlow，I found that：
  self.upsample = torch.nn.ConvTranspose1d(n_mel_channels,  n_mel_channels, 1024,stride=256）
   I guess stride is hop_length，but what is 1024 mean？it represents win_length or filter_length difined in config file ？
  THX for your reply

**Comment by Yeongtae** [comment]
,![image](https://user-images.githubusercontent.com/13597229/51300996-09d39a80-1a71-11e9-85c4-adc2fe76ef32.png)

maybe win_length (in general, filter_length >=win_length)
![image](https://user-images.githubusercontent.com/13597229/51301149-88303c80-1a71-11e9-9149-2f774f2530e1.png)

upsampling(ConvTranspose1d) is used for this purpose. f(melspectrogram[B, 80, T/256])= ~ audio[B, T] in range [-1, 1]
