### ISSUE TITLE
Please, someone help a noob!

### ISSUE THREAD

**Issue by BrysonMiller** [NVIDIA/waveglow#87]
All I want is to use the pretrained model to use it to convert my text into speech.
Can someone help me with that, please?

I can pay.

**Comment by rafaelvalle** [comment]
You need to use both Tacotron 2 and Waveglow.
Take a look here https://github.com/NVIDIA/tacotron2/

**Comment by Timbono** [comment]
I`m a total noob though. I don`t know how to program. Is there not a program that I an use, that uses Waveglow?
All I want is to convert my text into speech with waveglow. But  don`t know how to do it! :(
Someone help?

I can pay for it if someone can help me to get it to work.

**Comment by Cacozelia** [comment]
I'm having a similar problem getting Waveglow to work. There is no step by step guide for complete beginners, unfortunately.

**Comment by Timbono** [comment]
Yes! That's what we need, please!
A step-by-step guide for beginners, who just want to convert their text into speech with NVIDIA's Waveglow.

**Comment by rafaelvalle** [comment]
https://github.com/NVIDIA/tacotron2/
https://github.com/NVIDIA/tacotron2/blob/master/inference.ipynb

**Comment by Timbono** [comment]
> https://github.com/NVIDIA/tacotron2/
> https://github.com/NVIDIA/tacotron2/blob/master/inference.ipynb

Thank you Rafaelvalle. I see that you take up the effort to help us.
But how am I supposed to get this program to work, if I don't know how to program, and don't understand many of those special terms?

What we really need is a step-by-step tutorial on youtube, that we can follow. Please.

**Comment by ShikiSuen** [comment]
Note: The number 87 means "idiot" in Formosa local dialects.
(This is not talking about the OP but only the number of this thread.)

**Comment by Timbono** [comment]
I'm not an idiot, just unexperienced. Is there no program that uses NVIDIA's waveglow?
Something for the average person?

**Comment by Timbono** [comment]
Something like this would be nice:
https://www.youtube.com/watch?v=OSZ0nq--ihg

**Comment by Cacozelia** [comment]
Totally agree @Timbono, no need for veiled snarky comments. @ShikiSuen, if you add 8 and 7 together it makes 15. Which is not the total number of letters in ‘patronising’

**Comment by rohan6366** [comment]
@BrysonMiller 
1) Download this File -> https://github.com/yhgon/SMWU_DL/blob/master/inference_T2%2BWG_on_COLAB.ipynb

2) Go to Google Collaboratory
https://colab.research.google.com

3) Select the Upload option and choose the file downloaded on Step 1

4) After the notebook opens, select the Runtime dropdown from the menu, change runtime type, Hardware accelerator to GPU, Save.

5) Runtime (Menu) -> Run All

6) Scroll to the bottom of the notebook to view results 

7) Change input text from the Input Sentence Section 

Notebook By: https://github.com/yhgon

**Comment by BrysonMiller** [comment]
> 1. Download this File -> https://github.com/yhgon/SMWU_DL/blob/master/inference_T2%2BWG_on_COLAB.ipynb

Which file should I download, and how do I download it?

**Comment by BrysonMiller** [comment]
Do I need to download the zip file here, and upload the zip file?
https://github.com/yhgon/SMWU_DL

**Comment by rohan6366** [comment]
@BrysonMiller , go to the link I mentioned. Right click on 'Raw'-> Save Link as -> Save the file wherever you like. It's an IPYNB file

**Comment by BrysonMiller** [comment]
@rohan6366 
Thanks a lot, that worked! But unfortunately, I can't get any recordings that are longer than 1 or 2 sentences. If I give more than 2 sentences as input, the output interrupts after 11 seconds.
How do I increase the limit for the text that I can input?

**Comment by rafaelvalle** [comment]
Generate 2 sentences at a time.

**Comment by NinoSkopac** [comment]
@rafaelvalle Is this still a thing, only being able to convert 2 sentences at a time?

**Comment by CookiePPP** [comment]
@NinoSkopac 
To remove the Tacotron2 limit, update
https://github.com/NVIDIA/tacotron2/blob/master/hparams.py#L59
```
        max_decoder_steps=1000,
```
to whatever limit you need.
80 steps = 1 second.
Default limit is 12.5 seconds.

**Comment by NinoSkopac** [comment]
Nice, thanks for the answer.

Will this make inference noticeably slower?

**Comment by CookiePPP** [comment]
@NinoSkopac 
If you have to generate a paragraph.
It would be faster to split it into sentences and use batch inference to generate each sentence at the same time.
But if you **have** to generate with a single input, this would be good yes.

---

If you find stability issues with extremely long inputs, you may have to look at other repo's.
https://google.github.io/tacotron/publications/location_relative_attention/
The attention mechanism used in this repo can degrade as input length increases passed the length seen during training.

**Comment by CookiePPP** [comment]
@giuliogatto 
Could you extend the top error (the "8 frames" bit in the middle)?

---

Depending on your requirements, you could also turn one of these examples into what you need(?)

https://drive.google.com/open?id=19_S4oUc11S2N2FG-ybrwN455A74bbb85

https://drive.google.com/open?id=1p5Y6cqVAd9NTnFqQ7M11i4hG7M0DwvU2

**Comment by giuliogatto** [comment]
Thank you for your quick response!
Here's a gist with the full expanded error
https://gist.github.com/giuliogatto/daabad7c529beebd390eb1592ee090aa

**Comment by CookiePPP** [comment]
@giuliogatto 
:thinking: 
Seems like you will need to update something

**Comment by giuliogatto** [comment]
Yes I'll try and sort out the dependencies next, thanks!

**Comment by NinoSkopac** [comment]
@giuliogatto Goulio, I’m stuck at the same place as you, did you manage to figure it out?

**Comment by giuliogatto** [comment]
Sorry, not yet! Unluckily I didn't have time to try and fix the
dependencies!
