### ISSUE TITLE
why remove weight normalization when inference? 

### ISSUE THREAD

**Issue by wenyong-h** [NVIDIA/waveglow#9]
Will that hurt quality of the generated sample?
Or why it could still work if weight normalization is removed?

**Comment by bryancatanzaro** [comment]
Weight normalization isn't necessary during inference - you can just make the model have normalized weights and skip the extra computation.
https://arxiv.org/pdf/1602.07868.pdf

The resulting samples are the same.

**Comment by rafaelvalle** [comment]
https://github.com/NVIDIA/waveglow/blob/master/glow.py#L113

**Comment by bryancatanzaro** [comment]
If you look at the PyTorch implementation of weight norm, when it gets removed, it recomputes the weights:
https://pytorch.org/docs/stable/_modules/torch/nn/utils/weight_norm.html

**Comment by wenyong-h** [comment]
Ah, I see! They should describe that behavior in PyTorch doc.
Thanks for your patience!

**Comment by bryancatanzaro** [comment]
Of course! 👍
